## Importing libraries

In [1]:
!pip install statsmodels

Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (0.14.5)
Requirement already satisfied: numpy<3,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (2.0.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (1.16.3)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (2.2.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

In [2]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.18.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.11.12)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.4)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [3]:
# basic scientific stack
import numpy as np
import pandas as pd

# plotting
import plotly.express as px
import plotly.graph_objects as go

# model evaluation
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# model utilities
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# linear models
from sklearn.linear_model import (
    LinearRegression,
    Ridge,
    Lasso,
    HuberRegressor
)

# tree and ensemble models
from sklearn.ensemble import (
    RandomForestRegressor,
    HistGradientBoostingRegressor
)

# nearest neighbors
from sklearn.neighbors import KNeighborsRegressor

# neural network model
from sklearn.neural_network import MLPRegressor

# boosting model
from xgboost import XGBRegressor

# tensorflow for deep learning models
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import (
    Dense,
    LSTM,
    Input,
    Concatenate
)
from tensorflow.keras.callbacks import EarlyStopping

### IMPORTING DATA

In [4]:
from google.colab import files
uploaded = files.upload()

Saving manhattan (1).csv to manhattan (1).csv

In [13]:
from google.colab import files
uploaded = files.upload()

Saving usa_inflation (2).csv to usa_inflation (2).csv

In [6]:
 df = pd.read_csv("manhattan (1).csv")
df = df.drop(index=0)
df = df.reset_index(drop = True)
df.columns

Index(['BOROUGH\n', 'NEIGHBORHOOD\n', 'BUILDING CLASS CATEGORY\n',
       'TAX CLASS AS OF FINAL ROLL 18/19', 'BLOCK\n', 'LOT\n', 'EASE-MENT\n',
       'BUILDING CLASS AS OF FINAL ROLL 18/19', 'ADDRESS\n',
       'APARTMENT NUMBER\n', 'ZIP CODE\n', 'RESIDENTIAL UNITS\n',
       'COMMERCIAL UNITS\n', 'TOTAL UNITS\n', 'LAND SQUARE FEET\n',
       'GROSS SQUARE FEET\n', 'YEAR BUILT\n', 'TAX CLASS AT TIME OF SALE\n',
       'BUILDING CLASS AT TIME OF SALE\n', 'SALE PRICE\n', 'SALE DATE\n',
       'YEAR'],
      dtype='object')

In [14]:
usa_inflation = pd.read_csv("usa_inflation (2).csv",
    encoding="cp1252")

In [9]:
df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
    .str.replace("-", "_")
    .str.upper()
)

In [15]:
df

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_AS_OF_FINAL_ROLL_18/19,BLOCK,LOT,EASE_MENT,BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19,ADDRESS,APARTMENT_NUMBER,...,COMMERCIAL_UNITS,TOTAL_UNITS,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE PRICE,SALE_DATE,YEAR
0,1.0,ALPHABET CITY,01 ONE FAMILY DWELLINGS,1,390.0,61.0,NaN,A4,189 EAST 7TH STREET,NaN,...,0.0,1.0,987.0,2183.0,1860.0,1.0,A4,0.0,2019-09-25,2019.0
1,1.0,ALPHABET CITY,02 TWO FAMILY DWELLINGS,1,404.0,1.0,NaN,B9,166 AVENUE A,NaN,...,0.0,2.0,1510.0,4520.0,1900.0,1.0,B9,0.0,2019-07-22,2019.0
2,1.0,ALPHABET CITY,03 THREE FAMILY DWELLINGS,1,377.0,56.0,NaN,C0,263 EAST 7TH STREET,NaN,...,0.0,3.0,2430.0,3600.0,1899.0,1.0,C0,6300000.0,2019-04-30,2019.0
3,1.0,ALPHABET CITY,03 THREE FAMILY DWELLINGS,1,393.0,9.0,NaN,C0,604 EAST 11TH STREET,NaN,...,0.0,3.0,2375.0,5110.0,1939.0,1.0,C0,0.0,2019-10-24,2019.0
4,1.0,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,372.0,23.0,NaN,C1,300 EAST 3RD STREET,NaN,...,0.0,12.0,2393.0,7989.0,2001.0,2.0,C1,1950000.0,2019-08-08,2019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326765,1.0,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,2180.0,1211.0,,RG,736 WEST 187 STREET,PRK11,...,0.0,1.0,0.0,0.0,2003.0,4.0,RG,0.0,2014-04-22,2014.0
326766,1.0,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,2180.0,1216.0,,RG,736 WEST 187 STREET,PRK16,...,0.0,1.0,0.0,0.0,2003.0,4.0,RG,0.0,2014-06-04,2014.0
326767,1.0,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,2180.0,1217.0,,RG,736 WEST 187 STREET,PRK17,...,0.0,1.0,0.0,0.0,2003.0,4.0,RG,0.0,2014-06-16,2014.0
326768,1.0,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,2180.0,1220.0,,RG,736 WEST 187 STREET,PRK20,...,0.0,1.0,0.0,0.0,2003.0,4.0,RG,50000.0,2014-07-07,2014.0
326769,1.0,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,2180.0,1224.0,,RG,736 WEST 187 STREET,PRK24,...,0.0,1.0,0.0,0.0,2003.0,4.0,RG,0.0,2014-10-03,2014.0

In [16]:
df.rename(columns={"SALE_PRICE": "SALE PRICE"}, inplace=True)

## feature engineering

In [18]:
usa_inflation.head()

,Series Name,Series Code,Country Name,Country Code,2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,United States,USA,-0.355546,1.640043,3.156842,2.069337,1.464833,1.622223,0.118627,1.261583,2.13011,2.442583,1.81221,1.233584,4.697859,8.0028,4.116338,2.949525
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#. Drop unnecessary columns
usa_inflation = usa_inflation.drop(
    columns=['Series Name', 'Series Code', 'Country Name', 'Country Code'],
    errors='ignore')

In [20]:
usa_inflation.head()

,2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,-0.355546,1.640043,3.156842,2.069337,1.464833,1.622223,0.118627,1.261583,2.13011,2.442583,1.81221,1.233584,4.697859,8.0028,4.116338,2.949525
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# . Extract year columns (e.g. '2013 [YR2013]', ..., '2024 [YR2024]')
year_cols = [c for c in usa_inflation.columns if 'YR' in c]

In [22]:
# . Convert inflation rates to numeric
rates = usa_inflation.loc[0, year_cols].astype(float)

In [23]:
rates

2009 [YR2009]   -0.355546
2010 [YR2010]    1.640043
2011 [YR2011]    3.156842
2012 [YR2012]    2.069337
2013 [YR2013]    1.464833
2014 [YR2014]    1.622223
2015 [YR2015]    0.118627
2016 [YR2016]    1.261583
2017 [YR2017]    2.130110
2018 [YR2018]    2.442583
2019 [YR2019]    1.812210
2020 [YR2020]    1.233584
2021 [YR2021]    4.697859
2022 [YR2022]    8.002800
2023 [YR2023]    4.116338
2024 [YR2024]    2.949525
Name: 0, dtype: float64

In [24]:
# . Create inflation DataFrame
inflation_df = pd.DataFrame({
    'YEAR': [int(c.split()[0]) for c in year_cols],
    'INFLATION': rates.values  # <-- inflation rate for that year (%)
})

In [25]:
inflation_df

    YEAR  INFLATION
0   2009  -0.355546
1   2010   1.640043
2   2011   3.156842
3   2012   2.069337
4   2013   1.464833
5   2014   1.622223
6   2015   0.118627
7   2016   1.261583
8   2017   2.130110
9   2018   2.442583
10  2019   1.812210
11  2020   1.233584
12  2021   4.697859
13  2022   8.002800
14  2023   4.116338
15  2024   2.949525

In [26]:
# . Compute cumulative inflation up to 2024
inflation_df = inflation_df.sort_values('YEAR').reset_index(drop=True)
inflation_df['rate_frac'] = inflation_df['INFLATION'] / 100
inflation_df['price_index'] = (1 + inflation_df['rate_frac']).cumprod()

In [27]:
# . Calculate factor to adjust each year’s prices to 2024 values
price_index_2024 = inflation_df.loc[inflation_df['YEAR'] == 2024, 'price_index'].iloc[0]
inflation_df['inflation_factor'] = price_index_2024 / inflation_df['price_index']

In [28]:
print("Inflation DataFrame:")
print(inflation_df[['YEAR', 'INFLATION', 'inflation_factor']])

Inflation DataFrame:
    YEAR  INFLATION  inflation_factor
0   2009  -0.355546          1.462167
1   2010   1.640043          1.438573
2   2011   3.156842          1.394550
3   2012   2.069337          1.366277
4   2013   1.464833          1.346552
5   2014   1.622223          1.325057
6   2015   0.118627          1.323487
7   2016   1.261583          1.306998
8   2017   2.130110          1.279738
9   2018   2.442583          1.249225
10  2019   1.812210          1.226989
11  2020   1.233584          1.212037
12  2021   4.697859          1.157653
13  2022   8.002800          1.071873
14  2023   4.116338          1.029495
15  2024   2.949525          1.000000

In [29]:
pd.set_option('display.float_format', '{:,.0f}'.format)

In [30]:
#  grab the year columns from usa_inflation, they look like "2013 [YR2013]" etc
year_cols = [c for c in usa_inflation.columns if pd.Series(c).str.contains(r'^\s*\d{4}\s*\[YR\d{4}\]', regex=True).item()]

In [31]:
# rates row, assumes your file has one row of rates
rates_row = usa_inflation.loc[0, year_cols].astype(float)

In [32]:
# extract the year number, make a tidy frame
years = pd.Series(year_cols).str.extract(r'(\d{4})', expand=False).astype(int).to_list()
infl = pd.DataFrame({'YEAR': years, 'rate_pct': rates_row.values})

In [33]:
#  build a cumulative price index, base at first year, then compute factor to 2024
infl = infl.sort_values('YEAR').reset_index(drop=True)
infl['rate_frac'] = infl['rate_pct'] / 100.0
infl['index'] = (1.0 + infl['rate_frac']).cumprod()

In [34]:
# pick 2024 as target year, adjust if your target is different
target_year = 2024
target_idx = infl.loc[infl['YEAR'] == target_year, 'index'].iloc[0]
infl['to_2024_factor'] = target_idx / infl['index']

In [35]:
df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_AS_OF_FINAL_ROLL_18/19,BLOCK,LOT,EASE_MENT,BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19,ADDRESS,APARTMENT_NUMBER,...,COMMERCIAL_UNITS,TOTAL_UNITS,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE PRICE,SALE_DATE,YEAR
0,1,ALPHABET CITY,01 ONE FAMILY DWELLINGS,1,390,61,NaN,A4,189 EAST 7TH STREET,NaN,...,0,1,987,"2,183","1,860",1,A4,0,2019-09-25,"2,019"
1,1,ALPHABET CITY,02 TWO FAMILY DWELLINGS,1,404,1,NaN,B9,166 AVENUE A,NaN,...,0,2,"1,510","4,520","1,900",1,B9,0,2019-07-22,"2,019"
2,1,ALPHABET CITY,03 THREE FAMILY DWELLINGS,1,377,56,NaN,C0,263 EAST 7TH STREET,NaN,...,0,3,"2,430","3,600","1,899",1,C0,"6,300,000",2019-04-30,"2,019"
3,1,ALPHABET CITY,03 THREE FAMILY DWELLINGS,1,393,9,NaN,C0,604 EAST 11TH STREET,NaN,...,0,3,"2,375","5,110","1,939",1,C0,0,2019-10-24,"2,019"
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,372,23,NaN,C1,300 EAST 3RD STREET,NaN,...,0,12,"2,393","7,989","2,001",2,C1,"1,950,000",2019-08-08,"2,019"

In [36]:
# clean sale price and year in df, then merge the factor
df = df.copy()
df['SALE PRICE'] = pd.to_numeric(df['SALE PRICE'], errors='coerce')
df['YEAR'] = pd.to_numeric(df['YEAR'], errors='coerce').astype('Int64')

In [37]:
df = df.merge(infl[['YEAR', 'to_2024_factor']], on='YEAR', how='left')

In [38]:
# create the inflation adjusted price
df['INFLATION_ADJ_SALES'] = df['SALE PRICE'] * df['to_2024_factor']

In [39]:
df.columns

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING_CLASS_CATEGORY',
       'TAX_CLASS_AS_OF_FINAL_ROLL_18/19', 'BLOCK', 'LOT', 'EASE_MENT',
       'BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19', 'ADDRESS', 'APARTMENT_NUMBER',
       'ZIP_CODE', 'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS', 'TOTAL_UNITS',
       'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'YEAR_BUILT',
       'TAX_CLASS_AT_TIME_OF_SALE', 'BUILDING_CLASS_AT_TIME_OF_SALE',
       'SALE PRICE', 'SALE_DATE', 'YEAR', 'to_2024_factor',
       'INFLATION_ADJ_SALES'],
      dtype='object')

In [40]:
print(df[['SALE PRICE', 'YEAR', 'INFLATION_ADJ_SALES']].isnull().sum())

SALE PRICE             5
YEAR                   0
INFLATION_ADJ_SALES    5
dtype: int64

In [41]:
df['YEAR'].unique()

<IntegerArray>
[2019, 2015, 2011, 2016, 2012, 2018, 2009, 2020, 2021, 2013, 2024, 2017, 2023,
 2022, 2010, 2014]
Length: 16, dtype: Int64

In [42]:
print(df[['SALE PRICE', 'YEAR', 'INFLATION_ADJ_SALES']])

        SALE PRICE  YEAR  INFLATION_ADJ_SALES
0                0  2019                    0
1                0  2019                    0
2        6,300,000  2019            7,730,031
3                0  2019                    0
4        1,950,000  2019            2,392,629
...            ...   ...                  ...
326765           0  2014                    0
326766           0  2014                    0
326767           0  2014                    0
326768      50,000  2014               66,253
326769           0  2014                    0

[326770 rows x 3 columns]

In [43]:
df.columns

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING_CLASS_CATEGORY',
       'TAX_CLASS_AS_OF_FINAL_ROLL_18/19', 'BLOCK', 'LOT', 'EASE_MENT',
       'BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19', 'ADDRESS', 'APARTMENT_NUMBER',
       'ZIP_CODE', 'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS', 'TOTAL_UNITS',
       'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'YEAR_BUILT',
       'TAX_CLASS_AT_TIME_OF_SALE', 'BUILDING_CLASS_AT_TIME_OF_SALE',
       'SALE PRICE', 'SALE_DATE', 'YEAR', 'to_2024_factor',
       'INFLATION_ADJ_SALES'],
      dtype='object')

In [44]:
if "SALE_PRICE" in df.columns:
    df = df.drop(columns=["SALE_PRICE"])

In [45]:
df

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_AS_OF_FINAL_ROLL_18/19,BLOCK,LOT,EASE_MENT,BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19,ADDRESS,APARTMENT_NUMBER,...,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE PRICE,SALE_DATE,YEAR,to_2024_factor,INFLATION_ADJ_SALES
0,1,ALPHABET CITY,01 ONE FAMILY DWELLINGS,1,390,61,NaN,A4,189 EAST 7TH STREET,NaN,...,987,"2,183","1,860",1,A4,0,2019-09-25,2019,1,0
1,1,ALPHABET CITY,02 TWO FAMILY DWELLINGS,1,404,1,NaN,B9,166 AVENUE A,NaN,...,"1,510","4,520","1,900",1,B9,0,2019-07-22,2019,1,0
2,1,ALPHABET CITY,03 THREE FAMILY DWELLINGS,1,377,56,NaN,C0,263 EAST 7TH STREET,NaN,...,"2,430","3,600","1,899",1,C0,"6,300,000",2019-04-30,2019,1,"7,730,031"
3,1,ALPHABET CITY,03 THREE FAMILY DWELLINGS,1,393,9,NaN,C0,604 EAST 11TH STREET,NaN,...,"2,375","5,110","1,939",1,C0,0,2019-10-24,2019,1,0
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,372,23,NaN,C1,300 EAST 3RD STREET,NaN,...,"2,393","7,989","2,001",2,C1,"1,950,000",2019-08-08,2019,1,"2,392,629"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326765,1,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,"2,180","1,211",,RG,736 WEST 187 STREET,PRK11,...,0,0,"2,003",4,RG,0,2014-04-22,2014,1,0
326766,1,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,"2,180","1,216",,RG,736 WEST 187 STREET,PRK16,...,0,0,"2,003",4,RG,0,2014-06-04,2014,1,0
326767,1,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,"2,180","1,217",,RG,736 WEST 187 STREET,PRK17,...,0,0,"2,003",4,RG,0,2014-06-16,2014,1,0
326768,1,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,"2,180","1,220",,RG,736 WEST 187 STREET,PRK20,...,0,0,"2,003",4,RG,"50,000",2014-07-07,2014,1,"66,253"
326769,1,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,"2,180","1,224",,RG,736 WEST 187 STREET,PRK24,...,0,0,"2,003",4,RG,0,2014-10-03,2014,1,0

## EDA BEFORE Preprocessing

In [46]:
df.columns

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING_CLASS_CATEGORY',
       'TAX_CLASS_AS_OF_FINAL_ROLL_18/19', 'BLOCK', 'LOT', 'EASE_MENT',
       'BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19', 'ADDRESS', 'APARTMENT_NUMBER',
       'ZIP_CODE', 'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS', 'TOTAL_UNITS',
       'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'YEAR_BUILT',
       'TAX_CLASS_AT_TIME_OF_SALE', 'BUILDING_CLASS_AT_TIME_OF_SALE',
       'SALE PRICE', 'SALE_DATE', 'YEAR', 'to_2024_factor',
       'INFLATION_ADJ_SALES'],
      dtype='object')

In [47]:
(df['SALE PRICE'] == 0).sum()

np.int64(72026)

In [48]:
df = df[df['SALE PRICE'] > 0]

In [49]:
df['SALE PRICE'].count()

np.int64(254739)

In [50]:
(df['INFLATION_ADJ_SALES'] == 0).sum()

np.int64(0)

In [51]:
(df['INFLATION_ADJ_SALES'] == 0).sum()

np.int64(0)

In [52]:
df = df[df['INFLATION_ADJ_SALES'] > 0]

In [53]:
df[df['SALE PRICE'] == 0]

Empty DataFrame
Columns: [BOROUGH, NEIGHBORHOOD, BUILDING_CLASS_CATEGORY, TAX_CLASS_AS_OF_FINAL_ROLL_18/19, BLOCK, LOT, EASE_MENT, BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19, ADDRESS, APARTMENT_NUMBER, ZIP_CODE, RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS, LAND_SQUARE_FEET, GROSS_SQUARE_FEET, YEAR_BUILT, TAX_CLASS_AT_TIME_OF_SALE, BUILDING_CLASS_AT_TIME_OF_SALE, SALE PRICE, SALE_DATE, YEAR, to_2024_factor, INFLATION_ADJ_SALES]
Index: []

[0 rows x 24 columns]

In [54]:
df.tail()

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_AS_OF_FINAL_ROLL_18/19,BLOCK,LOT,EASE_MENT,BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19,ADDRESS,APARTMENT_NUMBER,...,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE PRICE,SALE_DATE,YEAR,to_2024_factor,INFLATION_ADJ_SALES
326754,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,"2,163",53,,K2,4250 BROADWAY,,...,"16,025","25,865","1,914",4,K2,"36,700,000",2014-12-08,2014,1,"48,629,579"
326759,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,"2,170",26,,V1,653 WEST 187 STREET,,...,"1,582",0,0,4,V1,"195,000",2014-04-09,2014,1,"258,386"
326763,1,WASHINGTON HEIGHTS UPPER,37 RELIGIOUS FACILITIES,4,"2,177",158,,M1,815 WEST 179TH STREET,,...,"5,075","8,624","1,967",4,M1,"2,580,000",2014-06-17,2014,1,"3,418,646"
326764,1,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,"2,180","1,204",,RG,736 WEST 187 STREET,PRK4,...,0,0,"2,003",4,RG,"30,000",2014-01-14,2014,1,"39,752"
326768,1,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,"2,180","1,220",,RG,736 WEST 187 STREET,PRK20,...,0,0,"2,003",4,RG,"50,000",2014-07-07,2014,1,"66,253"

In [55]:
df.columns

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING_CLASS_CATEGORY',
       'TAX_CLASS_AS_OF_FINAL_ROLL_18/19', 'BLOCK', 'LOT', 'EASE_MENT',
       'BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19', 'ADDRESS', 'APARTMENT_NUMBER',
       'ZIP_CODE', 'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS', 'TOTAL_UNITS',
       'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'YEAR_BUILT',
       'TAX_CLASS_AT_TIME_OF_SALE', 'BUILDING_CLASS_AT_TIME_OF_SALE',
       'SALE PRICE', 'SALE_DATE', 'YEAR', 'to_2024_factor',
       'INFLATION_ADJ_SALES'],
      dtype='object')

In [56]:

# 1. Compute yearly averages from df
df_year = (
    df.groupby("YEAR", as_index=False)
    .agg(
        original_price=("SALE PRICE", "mean"),
        inflation_price=("INFLATION_ADJ_SALES", "mean")
    )
)

# 2. Reshape to long format for plotting
df_long = df_year.melt(
    id_vars="YEAR",
    value_vars=["original_price", "inflation_price"],
    var_name="Type",
    value_name="Price"
)

# Optional nicer labels
df_long["Type"] = df_long["Type"].map({
    "original_price": "Original sale price",
    "inflation_price": "Inflation adjusted sale price (to 2024)"
})

# 3. Plot before vs after inflation
fig = px.line(
    df_long,
    x="YEAR",
    y="Price",
    color="Type",
    title="Original vs inflation adjusted sale prices over time (staten island)",
    markers=True
)

fig.update_layout(
    xaxis_title="Year",
    yaxis_title="Mean sale price",
    title_x=0.5,
    legend_title="Price type",
    height=600,
    width=1100
)

fig.update_yaxes(tickformat=",")

fig.show()

In [58]:
# nominal price growth
df_nominal = (
    df.groupby("YEAR", as_index=False)
      .agg(avg_nominal_price=("SALE PRICE", "mean"))
      .sort_values("YEAR")
)
df_nominal["nominal_growth"] = df_nominal["avg_nominal_price"].pct_change() * 100

# real price growth
df_real = (
    df.groupby("YEAR", as_index=False)
      .agg(avg_real_price=("INFLATION_ADJ_SALES", "mean"))
      .sort_values("YEAR")
)
df_real["real_growth"] = df_real["avg_real_price"].pct_change() * 100

# merge
df_growth = df_nominal.merge(df_real, on="YEAR")

# melt long format
df_long = df_growth.melt(
    id_vars="YEAR",
    value_vars=["nominal_growth", "real_growth"],
    var_name="Type",
    value_name="GrowthRate"
)

df_long["Type"] = df_long["Type"].map({
    "nominal_growth": "Nominal price growth",
    "real_growth": "Real price growth"
})

fig = px.line(
    df_long,
    x="YEAR",
    y="GrowthRate",
    color="Type",
    markers=True,
    title="Nominal vs Real Price Growth Rate, Percent Change"
)

fig.update_layout(
    xaxis_title="Year",
    yaxis_title="Growth rate percentage",
    title_x=0.5,
    height=600,
    width=950,
    legend_title="Type"
)

fig.add_hline(y=0, line_width=1, line_dash="dash", line_color="black")
fig.update_yaxes(tickformat=".1f")

fig.show()

In [ ]:
# Checks how many missing (NaN) values each column in df has
df.isnull().sum()

## Data Preprocessing

In [59]:
df.tail() # checkin the data

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_AS_OF_FINAL_ROLL_18/19,BLOCK,LOT,EASE_MENT,BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19,ADDRESS,APARTMENT_NUMBER,...,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE PRICE,SALE_DATE,YEAR,to_2024_factor,INFLATION_ADJ_SALES
326754,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,"2,163",53,,K2,4250 BROADWAY,,...,"16,025","25,865","1,914",4,K2,"36,700,000",2014-12-08,2014,1,"48,629,579"
326759,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,"2,170",26,,V1,653 WEST 187 STREET,,...,"1,582",0,0,4,V1,"195,000",2014-04-09,2014,1,"258,386"
326763,1,WASHINGTON HEIGHTS UPPER,37 RELIGIOUS FACILITIES,4,"2,177",158,,M1,815 WEST 179TH STREET,,...,"5,075","8,624","1,967",4,M1,"2,580,000",2014-06-17,2014,1,"3,418,646"
326764,1,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,"2,180","1,204",,RG,736 WEST 187 STREET,PRK4,...,0,0,"2,003",4,RG,"30,000",2014-01-14,2014,1,"39,752"
326768,1,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,"2,180","1,220",,RG,736 WEST 187 STREET,PRK20,...,0,0,"2,003",4,RG,"50,000",2014-07-07,2014,1,"66,253"

In [60]:
df.shape # checking the size of the data

(254739, 24)

In [61]:
df.columns = (
    df.columns.str.strip()            # remove leading/trailing spaces
              .str.replace("\n", " ") # replace line breaks with space
              .str.replace("\t", " ") # replace tabs with space
              .str.replace(" ", "_")  # replace spaces with underscores
              .str.upper()            # make them uppercase (optional)
)

print(df.columns)

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING_CLASS_CATEGORY',
       'TAX_CLASS_AS_OF_FINAL_ROLL_18/19', 'BLOCK', 'LOT', 'EASE_MENT',
       'BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19', 'ADDRESS', 'APARTMENT_NUMBER',
       'ZIP_CODE', 'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS', 'TOTAL_UNITS',
       'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'YEAR_BUILT',
       'TAX_CLASS_AT_TIME_OF_SALE', 'BUILDING_CLASS_AT_TIME_OF_SALE',
       'SALE_PRICE', 'SALE_DATE', 'YEAR', 'TO_2024_FACTOR',
       'INFLATION_ADJ_SALES'],
      dtype='object')

In [62]:
# Shows the number of rows and columns in df
df.shape

(254739, 24)

In [63]:
# Checks how many missing (NaN) values each column in df has
df.isnull().sum()

BOROUGH                                       0
NEIGHBORHOOD                                  0
BUILDING_CLASS_CATEGORY                       0
TAX_CLASS_AS_OF_FINAL_ROLL_18/19             80
BLOCK                                         0
LOT                                           0
EASE_MENT                                101026
BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19        80
ADDRESS                                       0
APARTMENT_NUMBER                          56368
ZIP_CODE                                      0
RESIDENTIAL_UNITS                         44326
COMMERCIAL_UNITS                          68961
TOTAL_UNITS                               42262
LAND_SQUARE_FEET                          71025
GROSS_SQUARE_FEET                         71025
YEAR_BUILT                                 8407
TAX_CLASS_AT_TIME_OF_SALE                     0
BUILDING_CLASS_AT_TIME_OF_SALE                0
SALE_PRICE                                    0
SALE_DATE                                     0
YEAR                                          0
TO_2024_FACTOR                                0
INFLATION_ADJ_SALES                           0
dtype: int64

In [64]:
# Displays the 'GROSS__SQUARE_FEET' column from the df DataFrame
df['GROSS_SQUARE_FEET']

2         3,600
4         7,989
5        17,478
7         4,154
8         3,491
          ...
326754   25,865
326759        0
326763    8,624
326764        0
326768        0
Name: GROSS_SQUARE_FEET, Length: 254739, dtype: float64

In [65]:
df.columns

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING_CLASS_CATEGORY',
       'TAX_CLASS_AS_OF_FINAL_ROLL_18/19', 'BLOCK', 'LOT', 'EASE_MENT',
       'BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19', 'ADDRESS', 'APARTMENT_NUMBER',
       'ZIP_CODE', 'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS', 'TOTAL_UNITS',
       'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'YEAR_BUILT',
       'TAX_CLASS_AT_TIME_OF_SALE', 'BUILDING_CLASS_AT_TIME_OF_SALE',
       'SALE_PRICE', 'SALE_DATE', 'YEAR', 'TO_2024_FACTOR',
       'INFLATION_ADJ_SALES'],
      dtype='object')

In [66]:
# Removes rows from df where 'GROSS__SQUARE_FEET' has missing values
df = df.dropna(subset=['GROSS_SQUARE_FEET'])

In [67]:
# Shows the number of rows and columns in the cleaned DataFrame
df.shape

(183714, 24)

In [68]:
# Checks how many missing (NaN) values remain in each column of the cleaned DataFrame
df.isnull().sum()

BOROUGH                                      0
NEIGHBORHOOD                                 0
BUILDING_CLASS_CATEGORY                      0
TAX_CLASS_AS_OF_FINAL_ROLL_18/19             0
BLOCK                                        0
LOT                                          0
EASE_MENT                                30001
BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19        0
ADDRESS                                      0
APARTMENT_NUMBER                         14057
ZIP_CODE                                     0
RESIDENTIAL_UNITS                            0
COMMERCIAL_UNITS                             0
TOTAL_UNITS                                  0
LAND_SQUARE_FEET                             0
GROSS_SQUARE_FEET                            0
YEAR_BUILT                                2314
TAX_CLASS_AT_TIME_OF_SALE                    0
BUILDING_CLASS_AT_TIME_OF_SALE               0
SALE_PRICE                                   0
SALE_DATE                                    0
YEAR                                         0
TO_2024_FACTOR                               0
INFLATION_ADJ_SALES                          0
dtype: int64

In [69]:
print(df['INFLATION_ADJ_SALES'].isnull().sum())

0

In [70]:
df

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_AS_OF_FINAL_ROLL_18/19,BLOCK,LOT,EASE_MENT,BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19,ADDRESS,APARTMENT_NUMBER,...,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE_PRICE,SALE_DATE,YEAR,TO_2024_FACTOR,INFLATION_ADJ_SALES
2,1,ALPHABET CITY,03 THREE FAMILY DWELLINGS,1,377,56,NaN,C0,263 EAST 7TH STREET,NaN,...,"2,430","3,600","1,899",1,C0,"6,300,000",2019-04-30,2019,1,"7,730,031"
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,372,23,NaN,C1,300 EAST 3RD STREET,NaN,...,"2,393","7,989","2,001",2,C1,"1,950,000",2019-08-08,2019,1,"2,392,629"
5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,373,19,NaN,C7,332 EAST 4TH STREET,NaN,...,"4,651","17,478","1,920",2,C7,"14,000,000",2019-01-09,2019,1,"17,177,846"
7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,376,23,NaN,C3,"262 EAST 7TH STREET, 4",NaN,...,"2,059","4,154","1,900",2,C3,"600,000",2019-12-12,2019,1,"736,193"
8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,376,26,NaN,C3,268 EAST 7TH STREET,NaN,...,"2,065","3,491","1,900",2,C3,"4,350,000",2019-10-31,2019,1,"5,337,402"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326754,1,WASHINGTON HEIGHTS UPPER,22 STORE BUILDINGS,4,"2,163",53,,K2,4250 BROADWAY,,...,"16,025","25,865","1,914",4,K2,"36,700,000",2014-12-08,2014,1,"48,629,579"
326759,1,WASHINGTON HEIGHTS UPPER,31 COMMERCIAL VACANT LAND,4,"2,170",26,,V1,653 WEST 187 STREET,,...,"1,582",0,0,4,V1,"195,000",2014-04-09,2014,1,"258,386"
326763,1,WASHINGTON HEIGHTS UPPER,37 RELIGIOUS FACILITIES,4,"2,177",158,,M1,815 WEST 179TH STREET,,...,"5,075","8,624","1,967",4,M1,"2,580,000",2014-06-17,2014,1,"3,418,646"
326764,1,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,"2,180","1,204",,RG,736 WEST 187 STREET,PRK4,...,0,0,"2,003",4,RG,"30,000",2014-01-14,2014,1,"39,752"
326768,1,WASHINGTON HEIGHTS UPPER,44 CONDO PARKING,4,"2,180","1,220",,RG,736 WEST 187 STREET,PRK20,...,0,0,"2,003",4,RG,"50,000",2014-07-07,2014,1,"66,253"

In [71]:
df.columns

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING_CLASS_CATEGORY',
       'TAX_CLASS_AS_OF_FINAL_ROLL_18/19', 'BLOCK', 'LOT', 'EASE_MENT',
       'BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19', 'ADDRESS', 'APARTMENT_NUMBER',
       'ZIP_CODE', 'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS', 'TOTAL_UNITS',
       'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'YEAR_BUILT',
       'TAX_CLASS_AT_TIME_OF_SALE', 'BUILDING_CLASS_AT_TIME_OF_SALE',
       'SALE_PRICE', 'SALE_DATE', 'YEAR', 'TO_2024_FACTOR',
       'INFLATION_ADJ_SALES'],
      dtype='object')

In [72]:
# Deletes the 'EASE-MENT' column from the DataFrame
df.drop(columns=['EASE_MENT'], inplace=True)

/tmp/ipython-input-4035023701.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [73]:
# Deletes the 'APARTMENT_NUMBER' column from the DataFrame
df.drop(columns=['APARTMENT_NUMBER'], inplace=True)

/tmp/ipython-input-553989296.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [74]:
# Displays the number of rows and columns after dropping all missing values
df.shape

(183714, 22)

In [75]:
# Removes all rows with any missing (NaN) values from the DataFrame
df = df.dropna()

In [76]:
# Function to standardize column names
def clean_columns(temp):
    temp = temp.rename(columns={
        'TOTAL__UNITS': 'TOTAL_UNITS',
        'LAND__SQUARE_FEET': 'LAND_SQUARE_FEET',
        'GROSS__SQUARE_FEET': 'GROSS_SQUARE_FEET'
    })
    return temp

# Apply to all your dataframes
df = clean_columns(df)

In [77]:
# Function to fix tax class column names
def fix_tax_class_columns(df):
    df = df.rename(columns={
        'TAX_CLASS_AS_OF_FINAL_ROLL_18/19': 'TAX_CLASS_AT_PRESENT',
        'BUILDING_CLASS_AS_OF_FINAL_ROLL_18/19': 'BUILDING_CLASS_AT_PRESENT'
    })
    return df

# Apply to all dataframes
df = fix_tax_class_columns(df)

In [78]:
df.shape

(181400, 22)

In [79]:
df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_AT_PRESENT,BLOCK,LOT,BUILDING_CLASS_AT_PRESENT,ADDRESS,ZIP_CODE,RESIDENTIAL_UNITS,...,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE_PRICE,SALE_DATE,YEAR,TO_2024_FACTOR,INFLATION_ADJ_SALES
2,1,ALPHABET CITY,03 THREE FAMILY DWELLINGS,1,377,56,C0,263 EAST 7TH STREET,"10,009",3,...,"2,430","3,600","1,899",1,C0,"6,300,000",2019-04-30,2019,1,"7,730,031"
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,372,23,C1,300 EAST 3RD STREET,"10,009",12,...,"2,393","7,989","2,001",2,C1,"1,950,000",2019-08-08,2019,1,"2,392,629"
5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,373,19,C7,332 EAST 4TH STREET,"10,009",28,...,"4,651","17,478","1,920",2,C7,"14,000,000",2019-01-09,2019,1,"17,177,846"
7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,376,23,C3,"262 EAST 7TH STREET, 4","10,009",4,...,"2,059","4,154","1,900",2,C3,"600,000",2019-12-12,2019,1,"736,193"
8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,376,26,C3,268 EAST 7TH STREET,"10,009",4,...,"2,065","3,491","1,900",2,C3,"4,350,000",2019-10-31,2019,1,"5,337,402"

In [80]:
df.columns

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING_CLASS_CATEGORY',
       'TAX_CLASS_AT_PRESENT', 'BLOCK', 'LOT', 'BUILDING_CLASS_AT_PRESENT',
       'ADDRESS', 'ZIP_CODE', 'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS',
       'TOTAL_UNITS', 'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'YEAR_BUILT',
       'TAX_CLASS_AT_TIME_OF_SALE', 'BUILDING_CLASS_AT_TIME_OF_SALE',
       'SALE_PRICE', 'SALE_DATE', 'YEAR', 'TO_2024_FACTOR',
       'INFLATION_ADJ_SALES'],
      dtype='object')

## EDA

In [81]:
import plotly.express as px
import pandas as pd

fig = px.box(
    df,
    y="INFLATION_ADJ_SALES",
    points="outliers",
    title=" staten island inflation adjusted sale price, box plot"
)

fig.update_layout(
    title_x=0.5,
    title_font=dict(size=20)
)

fig.show()

In [82]:
import pandas as pd
import plotly.express as px

# count how many sales happened each year
df_count = (
    df.groupby("YEAR", as_index=False)
      .agg(sales_count=("SALE_PRICE", "count"))
)

fig = px.bar(
    df_count,
    x="YEAR",
    y="sales_count",
    title="Number of Sales Per Year",
    text="sales_count"
)

fig.update_layout(
    xaxis_title="Year",
    yaxis_title="Number of sales",
    title_x=0.5,
    height=500,
    width=900
)

fig.update_traces(textposition="outside")

fig.show()

In [83]:
import pandas as pd
import plotly.express as px

# compute mean sale price per year
df_price = (
    df.groupby("YEAR", as_index=False)
      .agg(avg_price=("SALE_PRICE", "mean"))
)

# calculate year to year growth rate (percent)
df_price["price_growth_rate"] = df_price["avg_price"].pct_change() * 100

# plot
fig = px.line(
    df_price,
    x="YEAR",
    y="price_growth_rate",
    markers=True,
    title="Yearly Price Growth Rate (Percent Change)"
)

fig.update_layout(
    xaxis_title="Year",
    yaxis_title="Growth rate percentage",
    title_x=0.5,
    height=550,
    width=950
)

fig.add_hline(y=0, line_width=1, line_dash="dash", line_color="black")

fig.show()

In [84]:
import pandas as pd
import plotly.express as px

# compute mean inflation adjusted price per year
df_price_real = (
    df.groupby("YEAR", as_index=False)
      .agg(avg_real_price=("INFLATION_ADJ_SALES", "mean"))
)

# year to year real growth rate in percent
df_price_real["real_price_growth_rate"] = df_price_real["avg_real_price"].pct_change() * 100

fig = px.line(
    df_price_real,
    x="YEAR",
    y="real_price_growth_rate",
    markers=True,
    title="Yearly Real Price Growth Rate (Inflation Adjusted, Percent Change)"
)

fig.update_layout(
    xaxis_title="Year",
    yaxis_title="Real growth rate percentage",
    title_x=0.5,
    height=550,
    width=950
)

fig.add_hline(y=0, line_width=1, line_dash="dash", line_color="black")

fig.show()

In [85]:
import pandas as pd
import plotly.express as px

# nominal price growth
df_nominal = (
    df.groupby("YEAR", as_index=False)
      .agg(avg_nominal_price=("SALE_PRICE", "mean"))
)
df_nominal["nominal_growth"] = df_nominal["avg_nominal_price"].pct_change() * 100

# real price growth (inflation adjusted)
df_real = (
    df.groupby("YEAR", as_index=False)
      .agg(avg_real_price=("INFLATION_ADJ_SALES", "mean"))
)
df_real["real_growth"] = df_real["avg_real_price"].pct_change() * 100

# merge into one table
df_growth = df_nominal.merge(df_real, on="YEAR")

# melt to long format for plotting
df_long = df_growth.melt(
    id_vars="YEAR",
    value_vars=["nominal_growth", "real_growth"],
    var_name="Type",
    value_name="GrowthRate"
)

# rename for nicer labels
df_long["Type"] = df_long["Type"].map({
    "nominal_growth": "Nominal price growth (raw)",
    "real_growth": "Real price growth (inflation-adjusted)"
})

# plot
fig = px.line(
    df_long,
    x="YEAR",
    y="GrowthRate",
    color="Type",
    markers=True,
    title="Nominal vs Real Price Growth Rate (Percent Change)"
)

fig.update_layout(
    xaxis_title="Year",
    yaxis_title="Growth rate percentage",
    title_x=0.5,
    height=600,
    width=950,
    legend_title="Growth Type"
)

fig.add_hline(y=0, line_width=1, line_dash="dash", line_color="black")

fig.show()

In [86]:
df.columns

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING_CLASS_CATEGORY',
       'TAX_CLASS_AT_PRESENT', 'BLOCK', 'LOT', 'BUILDING_CLASS_AT_PRESENT',
       'ADDRESS', 'ZIP_CODE', 'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS',
       'TOTAL_UNITS', 'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'YEAR_BUILT',
       'TAX_CLASS_AT_TIME_OF_SALE', 'BUILDING_CLASS_AT_TIME_OF_SALE',
       'SALE_PRICE', 'SALE_DATE', 'YEAR', 'TO_2024_FACTOR',
       'INFLATION_ADJ_SALES'],
      dtype='object')

### before ml

In [87]:
# Print all column names so you can see the current structure
print(df.columns.tolist())

# Find the index position of the SALE_PRICE column
idx = np.where(df.columns == "SALE_PRICE")[0]
print(idx)

# Drop the SALE_PRICE column using its index position
# (This works but is more complicated than needed, you could drop by name directly)
df = df.drop(columns=[df.columns[idx[0]]], axis=1)

['BOROUGH', 'NEIGHBORHOOD', 'BUILDING_CLASS_CATEGORY', 'TAX_CLASS_AT_PRESENT', 'BLOCK', 'LOT', 'BUILDING_CLASS_AT_PRESENT', 'ADDRESS', 'ZIP_CODE', 'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS', 'TOTAL_UNITS', 'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'YEAR_BUILT', 'TAX_CLASS_AT_TIME_OF_SALE', 'BUILDING_CLASS_AT_TIME_OF_SALE', 'SALE_PRICE', 'SALE_DATE', 'YEAR', 'TO_2024_FACTOR', 'INFLATION_ADJ_SALES']
[17]

In [88]:
# Converts all object columns into numeric category codes
# This helps when you want to compute correlations or run simple models
def simple_encode(df):
    df = df.copy()
    for col in df.columns:
        # Check if the column contains text data
        if df[col].dtype == 'object':
            # Convert text values to category codes (integers)
            df[col] = df[col].astype('category').cat.codes
    return df

# Create an encoded version of the DataFrame where text columns are numeric
df_encoded = simple_encode(df)

# Compute a correlation matrix on the encoded numeric data
corr_matrix = df_encoded.corr()

# Display the correlation results
print(corr_matrix)

                                BOROUGH  NEIGHBORHOOD  \
BOROUGH                             NaN           NaN
NEIGHBORHOOD                        NaN             1
BUILDING_CLASS_CATEGORY             NaN             0
TAX_CLASS_AT_PRESENT                NaN             0
BLOCK                               NaN             0
LOT                                 NaN             0
BUILDING_CLASS_AT_PRESENT           NaN            -0
ADDRESS                             NaN            -0
ZIP_CODE                            NaN             0
RESIDENTIAL_UNITS                   NaN            -0
COMMERCIAL_UNITS                    NaN            -0
TOTAL_UNITS                         NaN            -0
LAND_SQUARE_FEET                    NaN            -0
GROSS_SQUARE_FEET                   NaN             0
YEAR_BUILT                          NaN            -0
TAX_CLASS_AT_TIME_OF_SALE           NaN             0
BUILDING_CLASS_AT_TIME_OF_SALE      NaN            -0
SALE_DATE                           NaN            -0
YEAR                                NaN            -0
TO_2024_FACTOR                      NaN             0
INFLATION_ADJ_SALES                 NaN            -0

                                BUILDING_CLASS_CATEGORY  TAX_CLASS_AT_PRESENT  \
BOROUGH                                             NaN                   NaN
NEIGHBORHOOD                                          0                     0
BUILDING_CLASS_CATEGORY                               1                     1
TAX_CLASS_AT_PRESENT                                  1                     1
BLOCK                                                -0                    -0
LOT                                                   0                    -0
BUILDING_CLASS_AT_PRESENT                             0                     0
ADDRESS                                              -0                    -0
ZIP_CODE                                             -0                     0
RESIDENTIAL_UNITS                                    -0                    -0
COMMERCIAL_UNITS                                      0                     0
TOTAL_UNITS                                          -0                    -0
LAND_SQUARE_FEET                                      0                     0
GROSS_SQUARE_FEET                                     0                     0
YEAR_BUILT                                           -0                    -0
TAX_CLASS_AT_TIME_OF_SALE                             1                     1
BUILDING_CLASS_AT_TIME_OF_SALE                        1                     0
SALE_DATE                                            -0                    -0
YEAR                                                 -0                    -0
TO_2024_FACTOR                                        0                     0
INFLATION_ADJ_SALES                                   0                     0

                                BLOCK  LOT  BUILDING_CLASS_AT_PRESENT  \
BOROUGH                           NaN  NaN                        NaN
NEIGHBORHOOD                        0    0                         -0
BUILDING_CLASS_CATEGORY            -0    0                          0
TAX_CLASS_AT_PRESENT               -0   -0                          0
BLOCK                               1   -0                         -0
LOT                                -0    1                          1
BUILDING_CLASS_AT_PRESENT          -0    1                          1
ADDRESS                             0    0                          0
ZIP_CODE                            0   -0                          0
RESIDENTIAL_UNITS                  -0   -0                         -0
COMMERCIAL_UNITS                   -0   -0                         -0
TOTAL_UNITS                        -0   -0                         -0
LAND_SQUARE_FEET                    0   -0                         -0
GROSS_SQUARE_FEET                  -0   -0                         -0
YEAR_BUILT                          0   -0                         -0
TAX_CLASS_AT_TIME_OF_SALE          -0    0                          0
BUILDING_CLASS_AT_TIME_OF_SALE     -0    1                          1
SALE_DATE                           0   -0                         -0
YEAR                                0   -0                         -0
TO_2024_FACTOR                     -0    0                          0
INFLATION_ADJ_SALES                -0   -0                          0

                                ADDRESS  ZIP_CODE  RESIDENTIAL_UNITS  ...  \
BOROUGH                             NaN       NaN                NaN  ...
NEIGHBORHOOD                         -0         0                 -0  ...
BUILDING_CLASS_CATEGORY              -0        -0                 -0  ...
TAX_CLASS_AT_PRESENT                 -0         0                 -0  ...
BLOCK                                 0         0                 -0  ...
LOT                                   0        -0                 -0  ...
BUILDING_CLASS_AT_PRESENT             0         0                 -0  ...
ADDRESS                               1         0                  0  ...
ZIP_CODE                              0         1                  0  ...
RESIDENTIAL_UNITS                     0         0                  1  ...
COMMERCIAL_UNITS                     -0         0                  0  ...
TOTAL_UNITS                           0         0                  1  ...
LAND_SQUARE_FEET                     -0         0                  0  ...
GROSS_SQUARE_FEET                    -0         0                  1  ...
YEAR_BUILT                           -0         0                  0  ...
TAX_CLASS_AT_TIME_OF_SALE            -0        -0                 -0  ...
BUILDING_CLASS_AT_TIME_OF_SALE        0        -0                 -0  ...
SALE_DATE                             0        -0                  0  ...
YEAR                                  0        -0                  0  ...
TO_2024_FACTOR                       -0         0                 -0  ...
INFLATION_ADJ_SALES                   0        -0                  0  ...

                                TOTAL_UNITS  LAND_SQUARE_FEET  \
BOROUGH                                 NaN               NaN
NEIGHBORHOOD                             -0                -0
BUILDING_CLASS_CATEGORY                  -0                 0
TAX_CLASS_AT_PRESENT                     -0                 0
BLOCK                                    -0                 0
LOT                                      -0                -0
BUILDING_CLASS_AT_PRESENT                -0                -0
ADDRESS                                   0                -0
ZIP_CODE                                  0                 0
RESIDENTIAL_UNITS                         1                 0
COMMERCIAL_UNITS                          0                 0
TOTAL_UNITS                               1                 0
LAND_SQUARE_FEET                          0                 1
GROSS_SQUARE_FEET                         1                 0
YEAR_BUILT                                0                 0
TAX_CLASS_AT_TIME_OF_SALE                -0                 0
BUILDING_CLASS_AT_TIME_OF_SALE           -0                -0
SALE_DATE                                 0                 0
YEAR                                      0                 0
TO_2024_FACTOR                           -0                -0
INFLATION_ADJ_SALES                       0                 0

                                GROSS_SQUARE_FEET  YEAR_BUILT  \
BOROUGH                                       NaN         NaN
NEIGHBORHOOD                                    0          -0
BUILDING_CLASS_CATEGORY                         0          -0
TAX_CLASS_AT_PRESENT                            0          -0
BLOCK                                          -0           0
LOT                                            -0          -0
BUILDING_CLASS_AT_PRESENT                      -0          -0
ADDRESS                                        -0          -0
ZIP_CODE                                        0           0
RESIDENTIAL_UNITS                               1           0
COMMERCIAL_UNITS                                0           0
TOTAL_UNITS                                     1           0
LAND_SQUARE_FEET                                0           0
GROSS_SQUARE_FEET                               1           0
YEAR_BUILT                                      0           1
TAX_CLASS_AT_TIME_OF_SALE                       0          -0
BUILDING_CLASS_AT_TIME_OF_SALE                 -0          -0
SALE_DATE                                       0           0
YEAR                                            0           0
TO_2024_FACTOR                                 -0          -0
INFLATION_ADJ_SALES                             0           0

                                TAX_CLASS_AT_TIME_OF_SALE  \
BOROUGH                                               NaN
NEIGHBORHOOD                                            0
BUILDING_CLASS_CATEGORY                                 1
TAX_CLASS_AT_PRESENT                                    1
BLOCK                                                  -0
LOT                                                     0
BUILDING_CLASS_AT_PRESENT                               0
ADDRESS                                                -0
ZIP_CODE                                               -0
RESIDENTIAL_UNITS                                      -0
COMMERCIAL_UNITS                                        0
TOTAL_UNITS                                            -0
LAND_SQUARE_FEET                                        0
GROSS_SQUARE_FEET                                       0
YEAR_BUILT                                             -0
TAX_CLASS_AT_TIME_OF_SALE                               1
BUILDING_CLASS_AT_TIME_OF_SALE                          0
SALE_DATE                                              -0
YEAR                                                   -0
TO_2024_FACTOR                                          0
INFLATION_ADJ_SALES                                     0

                                BUILDING_CLASS_AT_TIME_OF_SALE  SALE_DATE  \
BOROUGH                                                    NaN        NaN
NEIGHBORHOOD                                                -0         -0
BUILDING_CLASS_CATEGORY                                      1         -0
TAX_CLASS_AT_PRESENT                                         0         -0
BLOCK                                                       -0          0
LOT                                                          1         -0
BUILDING_CLASS_AT_PRESENT                                    1         -0
ADDRESS                                                      0          0
ZIP_CODE                                                    -0         -0
RESIDENTIAL_UNITS                                           -0          0
COMMERCIAL_UNITS                                            -0          0
TOTAL_UNITS                                                 -0          0
LAND_SQUARE_FEET                                            -0          0
GROSS_SQUARE_FEET                                           -0          0
YEAR_BUILT                                                  -0          0
TAX_CLASS_AT_TIME_OF_SALE                                    0         -0
BUILDING_CLASS_AT_TIME_OF_SALE                               1         -0
SALE_DATE                                                   -0          1
YEAR                                                        -0          1
TO_2024_FACTOR                                               0         -1
INFLATION_ADJ_SALES                                          0          0

                                YEAR  TO_2024_FACTOR  INFLATION_ADJ_SALES
BOROUGH                          NaN             NaN                  NaN
NEIGHBORHOOD                      -0               0                   -0
BUILDING_CLASS_CATEGORY           -0               0                    0
TAX_CLASS_AT_PRESENT              -0               0                    0
BLOCK                              0              -0                   -0
LOT                               -0               0                   -0
BUILDING_CLASS_AT_PRESENT         -0               0                    0
ADDRESS                            0              -0                    0
ZIP_CODE                          -0               0                   -0
RESIDENTIAL_UNITS                  0              -0                    0
COMMERCIAL_UNITS                   0              -0                    0
TOTAL_UNITS                        0              -0                    0
LAND_SQUARE_FEET                   0              -0                    0
GROSS_SQUARE_FEET                  0              -0                    0
YEAR_BUILT                         0              -0                    0
TAX_CLASS_AT_TIME_OF_SALE         -0               0                    0
BUILDING_CLASS_AT_TIME_OF_SALE    -0               0                    0
SALE_DATE                          1              -1                    0
YEAR                               1              -1                    0
TO_2024_FACTOR                    -1               1                   -0
INFLATION_ADJ_SALES                0              -0                    1

[21 rows x 21 columns]

In [89]:
fig = px.imshow(
    corr_matrix,
    text_auto=".2f",
    color_continuous_scale="Viridis",
    aspect="auto",
    title="Correlation Matrix"
)

fig.update_layout(
    width=900,
    height=900,
    title_x=0.5,
    title_font=dict(size=22),
    margin=dict(b=200)
)

fig.update_xaxes(
    tickangle=45,
    tickfont=dict(size=9),
    automargin=True
)

fig.update_yaxes(
    tickfont=dict(size=9),
    automargin=True
)

fig.show()

In [90]:
# Creates two tables: one for positive and one for negative correlations
# Helps identify which features move together or in opposite directions

def positive_negative_corr_tables(corr: pd.DataFrame, min_abs=0.0):
    # Mask upper triangle to avoid duplicate pairs and self-correlations
    mask = np.triu(np.ones_like(corr, dtype=bool), k=1)
    corr_ut = corr.where(mask)

    # Convert correlation matrix to long format
    pairs = (
        corr_ut.stack()
        .reset_index()
        .rename(columns={"level_0": "Column A", "level_1": "Column B", 0: "corr"})
    )

    # Filter correlations by absolute value threshold if specified
    if min_abs > 0:
        pairs = pairs[pairs["corr"].abs() >= min_abs]

    # Separate positive and negative correlations
    pos_df = pairs[pairs["corr"] > 0].sort_values("corr", ascending=False).reset_index(drop=True)
    neg_df = pairs[pairs["corr"] < 0].sort_values("corr", ascending=True).reset_index(drop=True)

    return pos_df, neg_df

# Example usage: get positive and negative correlation tables
pos_df, neg_df = positive_negative_corr_tables(corr_matrix, min_abs=0.0)

# Style the positive correlation table in green
pos_styled = (
    pos_df.style
    .background_gradient(subset=["corr"], cmap="Greens")
    .format({"corr": "{:.2f}"})
    .set_caption("Positive correlations")
)

# Style the negative correlation table in red
neg_styled = (
    neg_df.style
    .background_gradient(subset=["corr"], cmap="Reds")
    .format({"corr": "{:.2f}"})
    .set_caption("Negative correlations")
)

# Display styled tables (works in Jupyter or notebook environments)
pos_styled
neg_styled

In [91]:
# Creates two tables: one for positive and one for negative correlations
# Helps identify which features move together or in opposite directions

def positive_negative_corr_tables(corr: pd.DataFrame, min_abs=0.0):
    # Mask upper triangle to avoid duplicate pairs and self-correlations
    mask = np.triu(np.ones_like(corr, dtype=bool), k=1)
    corr_ut = corr.where(mask)

    # Convert correlation matrix to long format
    pairs = (
        corr_ut.stack()
        .reset_index()
        .rename(columns={"level_0": "Column A", "level_1": "Column B", 0: "corr"})
    )

    # Filter correlations by absolute value threshold if specified
    if min_abs > 0:
        pairs = pairs[pairs["corr"].abs() >= min_abs]

    # Separate positive and negative correlations
    pos_df = pairs[pairs["corr"] > 0].sort_values("corr", ascending=False).reset_index(drop=True)
    neg_df = pairs[pairs["corr"] < 0].sort_values("corr", ascending=True).reset_index(drop=True)

    return pos_df, neg_df

# Example usage: get positive and negative correlation tables
pos_df, neg_df = positive_negative_corr_tables(corr_matrix, min_abs=0.0)

# Style the positive correlation table in green
pos_styled = (
    pos_df.style
    .background_gradient(subset=["corr"], cmap="Greens")
    .format({"corr": "{:.2f}"})
    .set_caption("Positive correlations")
)

# Style the negative correlation table in red
neg_styled = (
    neg_df.style
    .background_gradient(subset=["corr"], cmap="Reds")
    .format({"corr": "{:.2f}"})
    .set_caption("Negative correlations")
)

# Display styled tables (works in Jupyter or notebook environments)
pos_styled

## ML

In [92]:
df["BUILDING_CLASS_CATEGORY"].unique()

array(['03 THREE FAMILY DWELLINGS', '07 RENTALS - WALKUP APARTMENTS',
       '08 RENTALS - ELEVATOR APARTMENTS',
       '13 CONDOS - ELEVATOR APARTMENTS', '14 RENTALS - 4-10 UNIT',
       '15 CONDOS - 2-10 UNIT RESIDENTIAL',
       '16 CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT',
       '47 CONDO NON-BUSINESS STORAGE', '01 ONE FAMILY DWELLINGS',
       '02 TWO FAMILY DWELLINGS', '12 CONDOS - WALKUP APARTMENTS',
       '21 OFFICE BUILDINGS', '22 STORE BUILDINGS', '23 LOFT BUILDINGS',
       '29 COMMERCIAL GARAGES', '30 WAREHOUSES',
       '31 COMMERCIAL VACANT LAND', '45 CONDO HOTELS',
       '46 CONDO STORE BUILDINGS', '43 CONDO OFFICE BUILDINGS',
       '26 OTHER HOTELS', '32 HOSPITAL AND HEALTH FACILITIES',
       '34 THEATRES', '35 INDOOR PUBLIC AND CULTURAL FACILITIES',
       '44 CONDO PARKING', '25 LUXURY HOTELS', '27 FACTORIES',
       '28 COMMERCIAL CONDOS', '33 EDUCATIONAL FACILITIES',
       '37 RELIGIOUS FACILITIES', '04 TAX CLASS 1 CONDOS',
       '42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC',
       '11 SPECIAL CONDO BILLING LOTS', '41 TAX CLASS 4 - OTHER',
       '06 TAX CLASS 1 - OTHER',
       '01  ONE FAMILY DWELLINGS                    ',
       '03  THREE FAMILY DWELLINGS                  ',
       '04  TAX CLASS 1 CONDOS                      ',
       '07  RENTALS - WALKUP APARTMENTS             ',
       '08  RENTALS - ELEVATOR APARTMENTS           ',
       '09  COOPS - WALKUP APARTMENTS               ',
       '10  COOPS - ELEVATOR APARTMENTS             ',
       '12  CONDOS - WALKUP APARTMENTS              ',
       '13  CONDOS - ELEVATOR APARTMENTS            ',
       '15  CONDOS - 2-10 UNIT RESIDENTIAL          ',
       '16  CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT ',
       '17  CONDO COOPS                             ',
       '22  STORE BUILDINGS                         ',
       '30  WAREHOUSES                              ',
       '31  COMMERCIAL VACANT LAND                  ',
       '46  CONDO STORE BUILDINGS                   ',
       '02  TWO FAMILY DWELLINGS                    ',
       '11A CONDO-RENTALS                           ',
       '14  RENTALS - 4-10 UNIT                     ',
       '21  OFFICE BUILDINGS                        ',
       '23  LOFT BUILDINGS                          ',
       '26  OTHER HOTELS                            ',
       '28  COMMERCIAL CONDOS                       ',
       '29  COMMERCIAL GARAGES                      ',
       '33  EDUCATIONAL FACILITIES                  ',
       '34  THEATRES                                ',
       '42  CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC  ',
       '43  CONDO OFFICE BUILDINGS                  ',
       '44  CONDO PARKING                           ',
       '47  CONDO NON-BUSINESS STORAGE              ',
       '49  CONDO WAREHOUSES/FACTORY/INDUS          ',
       '32  HOSPITAL AND HEALTH FACILITIES          ',
       '41  TAX CLASS 4 - OTHER                     ',
       '38  ASYLUMS AND HOMES                       ',
       '48  CONDO TERRACES/GARDENS/CABANAS          ',
       '25  LUXURY HOTELS                           ',
       '27  FACTORIES                               ',
       '37  RELIGIOUS FACILITIES                    ',
       '45  CONDO HOTELS                            ',
       '35  INDOOR PUBLIC AND CULTURAL FACILITIES   ',
       '36  OUTDOOR RECREATIONAL FACILITIES         ',
       '40  SELECTED GOVERNMENTAL FACILITIES        ',
       '01  ONE FAMILY HOMES                        ',
       '17  CONDOPS                                 ',
       '02  TWO FAMILY HOMES                        ',
       '03  THREE FAMILY HOMES                      ',
       '39  TRANSPORTATION FACILITIES               ',
       '                                            ',
       '09 COOPS - WALKUP APARTMENTS', '10 COOPS - ELEVATOR APARTMENTS',
       '17 CONDO COOPS', '38 ASYLUMS AND HOMES', '11A CONDO-RENTALS',
       '49 CONDO WAREHOUSES/FACTORY/INDUS',
       '48 CONDO TERRACES/GARDENS/CABANAS',
       '39 TRANSPORTATION FACILITIES',
       '11  SPECIAL CONDO BILLING LOTS              ',
       '07 RENTALS - WALKUP APARTMENTS             ',
       '09 COOPS - WALKUP APARTMENTS               ',
       '10 COOPS - ELEVATOR APARTMENTS             ',
       '12 CONDOS - WALKUP APARTMENTS              ',
       '13 CONDOS - ELEVATOR APARTMENTS            ',
       '14 RENTALS - 4-10 UNIT                     ',
       '15 CONDOS - 2-10 UNIT RESIDENTIAL          ',
       '16 CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT ',
       '17 CONDO COOPS                             ',
       '46 CONDO STORE BUILDINGS                   ',
       '01 ONE FAMILY DWELLINGS                    ',
       '02 TWO FAMILY DWELLINGS                    ',
       '03 THREE FAMILY DWELLINGS                  ',
       '04 TAX CLASS 1 CONDOS                      ',
       '08 RENTALS - ELEVATOR APARTMENTS           ',
       '21 OFFICE BUILDINGS                        ',
       '22 STORE BUILDINGS                         ',
       '23 LOFT BUILDINGS                          ',
       '26 OTHER HOTELS                            ',
       '29 COMMERCIAL GARAGES                      ',
       '30 WAREHOUSES                              ',
       '34 THEATRES                                ',
       '38 ASYLUMS AND HOMES                       ',
       '43 CONDO OFFICE BUILDINGS                  ',
       '44 CONDO PARKING                           ',
       '28 COMMERCIAL CONDOS                       ',
       '45 CONDO HOTELS                            ',
       '47 CONDO NON-BUSINESS STORAGE              ',
       '31 COMMERCIAL VACANT LAND                  ',
       '37 RELIGIOUS FACILITIES                    ',
       '41 TAX CLASS 4 - OTHER                     ',
       '25 LUXURY HOTELS                           ',
       '49 CONDO WAREHOUSES/FACTORY/INDUS          ',
       '27 FACTORIES                               ',
       '36 OUTDOOR RECREATIONAL FACILITIES         ',
       '40 SELECTED GOVERNMENTAL FACILITIES        ',
       '32 HOSPITAL AND HEALTH FACILITIES          ',
       '42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC  ',
       '33 EDUCATIONAL FACILITIES                  ',
       '35 INDOOR PUBLIC AND CULTURAL FACILITIES   ',
       '18  TAX CLASS 3 - UTILITY PROPERTIES        '], dtype=object)

In [93]:
mapping = {
    "01 ONE FAMILY DWELLINGS": "SINGLE_FAMILY",
    "02 TWO FAMILY DWELLINGS": "MULTI_FAMILY_SMALL",
    "03 THREE FAMILY DWELLINGS": "MULTI_FAMILY_SMALL",

    "04 TAX CLASS 1 CONDOS": "CONDO_COOP",
    "05 TAX CLASS 1 VACANT LAND": "VACANT_LAND",
    "06 TAX CLASS 1 - OTHER": "SINGLE_FAMILY",
    "07 RENTALS - WALKUP APARTMENTS": "MULTI_FAMILY_LARGE",
    "08 RENTALS - ELEVATOR APARTMENTS": "MULTI_FAMILY_LARGE",
    "09 COOPS - WALKUP APARTMENTS": "CONDO_COOP",
    "10 COOPS - ELEVATOR APARTMENTS": "CONDO_COOP",
    "11 SPECIAL CONDO BILLING LOTS": "CONDO_COOP",
    "11A CONDO-RENTALS": "CONDO_COOP",
    "12 CONDOS - WALKUP APARTMENTS": "CONDO_COOP",
    "13 CONDOS - ELEVATOR APARTMENTS": "CONDO_COOP",
    "14 RENTALS - 4-10 UNIT": "MULTI_FAMILY_LARGE",
    "15 CONDOS - 2-10 UNIT RESIDENTIAL": "CONDO_COOP",
    "17 CONDO COOPS": "CONDO_COOP",

    "18 TAX CLASS 3 - UNTILITY PROPERTIES": "COMMERCIAL",
    "21 OFFICE BUILDINGS": "COMMERCIAL",
    "22 STORE BUILDINGS": "COMMERCIAL",
    "23 LOFT BUILDINGS": "COMMERCIAL",
    "26 OTHER HOTELS": "COMMERCIAL",
    "27 FACTORIES": "COMMERCIAL",
    "28 COMMERCIAL CONDOS": "COMMERCIAL",
    "29 COMMERCIAL GARAGES": "COMMERCIAL",
    "30 WAREHOUSES": "COMMERCIAL",
    "31 COMMERCIAL VACANT LAND": "VACANT_LAND",
    "32 HOSPITAL AND HEALTH FACILITIES": "SPECIAL_USE",
    "33 EDUCATIONAL FACILITIES": "SPECIAL_USE",
    "34 THEATRES": "SPECIAL_USE",
    "35 INDOOR PUBLIC AND CULTURAL FACILITIES": "SPECIAL_USE",
    "36 OUTDOOR RECREATIONAL FACILITIES": "SPECIAL_USE",
    "37 RELIGIOUS FACILITIES": "SPECIAL_USE",
    "38 ASYLUMS AND HOMES": "SPECIAL_USE",
    "39 TRANSPORTATION FACILITIES": "SPECIAL_USE",
    "40 SELECTED GOVERNMENTAL FACILITIES": "SPECIAL_USE",
    "41 TAX CLASS 4 - OTHER": "COMMERCIAL",
    "42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC": "SPECIAL_USE",
    "43 CONDO OFFICE BUILDINGS": "COMMERCIAL",
    "44 CONDO PARKING": "COMMERCIAL",
    "46 CONDO STORE BUILDINGS": "COMMERCIAL",
    "47 CONDO NON BUSINESS STORAGE": "COMMERCIAL"
}

In [94]:
data = df.copy()

In [95]:
if "INFLATION_ADJ_SALES" not in data.columns:
    if "SALE_PRICE" in data.columns and "TO_2024_FACTOR" in data.columns:
        data["INFLATION_ADJ_SALES"] = data["SALE_PRICE"] * data["TO_2024_FACTOR"]
    else:
        raise ValueError("Need SALE_PRICE and TO_2024_FACTOR to compute INFLATION_ADJ_SALES")

In [96]:
if "SALE_DATE" in data.columns:
    data["SALE_DATE"] = pd.to_datetime(data["SALE_DATE"], errors="coerce")
    data["SALE_YEAR"] = data["SALE_DATE"].dt.year
    data["SALE_MONTH"] = data["SALE_DATE"].dt.month
    data["SALE_DAY"] = data["SALE_DATE"].dt.day

    data["SALE_YEAR"] = data["SALE_YEAR"].fillna(0).astype(int)
    data["SALE_MONTH"] = data["SALE_MONTH"].fillna(0).astype(int)
    data["SALE_DAY"] = data["SALE_DAY"].fillna(0).astype(int)

    data = data.drop(columns=["SALE_DATE"])

In [97]:
# make sure we have the raw category column
if "BUILDING_CLASS_CATEGORY" not in data.columns:
    raise ValueError("BUILDING_CLASS_CATEGORY not in data, run this on the df before get_dummies")

# clean spaces so mapping keys match
data["BUILDING_CLASS_CATEGORY"] = data["BUILDING_CLASS_CATEGORY"].str.strip()

# map to condensed group
data["CATEGORY_GROUP"] = data["BUILDING_CLASS_CATEGORY"].map(mapping)

# optional, check for any categories that did not map
unmapped = data.loc[data["CATEGORY_GROUP"].isna(), "BUILDING_CLASS_CATEGORY"].unique()
print("Unmapped categories:", unmapped)

Unmapped categories: ['16 CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT'
 '47 CONDO NON-BUSINESS STORAGE' '45 CONDO HOTELS' '25 LUXURY HOTELS'
 '01  ONE FAMILY DWELLINGS' '03  THREE FAMILY DWELLINGS'
 '04  TAX CLASS 1 CONDOS' '07  RENTALS - WALKUP APARTMENTS'
 '08  RENTALS - ELEVATOR APARTMENTS' '09  COOPS - WALKUP APARTMENTS'
 '10  COOPS - ELEVATOR APARTMENTS' '12  CONDOS - WALKUP APARTMENTS'
 '13  CONDOS - ELEVATOR APARTMENTS' '15  CONDOS - 2-10 UNIT RESIDENTIAL'
 '16  CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT' '17  CONDO COOPS'
 '22  STORE BUILDINGS' '30  WAREHOUSES' '31  COMMERCIAL VACANT LAND'
 '46  CONDO STORE BUILDINGS' '02  TWO FAMILY DWELLINGS'
 '14  RENTALS - 4-10 UNIT' '21  OFFICE BUILDINGS' '23  LOFT BUILDINGS'
 '26  OTHER HOTELS' '28  COMMERCIAL CONDOS' '29  COMMERCIAL GARAGES'
 '33  EDUCATIONAL FACILITIES' '34  THEATRES'
 '42  CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC' '43  CONDO OFFICE BUILDINGS'
 '44  CONDO PARKING' '47  CONDO NON-BUSINESS STORAGE'
 '49  CONDO WAREHOUSES/FACTORY/INDUS' '32  HOSPITAL AND HEALTH FACILITIES'
 '41  TAX CLASS 4 - OTHER' '38  ASYLUMS AND HOMES'
 '48  CONDO TERRACES/GARDENS/CABANAS' '25  LUXURY HOTELS' '27  FACTORIES'
 '37  RELIGIOUS FACILITIES' '45  CONDO HOTELS'
 '35  INDOOR PUBLIC AND CULTURAL FACILITIES'
 '36  OUTDOOR RECREATIONAL FACILITIES'
 '40  SELECTED GOVERNMENTAL FACILITIES' '01  ONE FAMILY HOMES'
 '17  CONDOPS' '02  TWO FAMILY HOMES' '03  THREE FAMILY HOMES'
 '39  TRANSPORTATION FACILITIES' '' '49 CONDO WAREHOUSES/FACTORY/INDUS'
 '48 CONDO TERRACES/GARDENS/CABANAS' '11  SPECIAL CONDO BILLING LOTS'
 '18  TAX CLASS 3 - UTILITY PROPERTIES']

In [98]:
data["CATEGORY_GROUP"] = data["CATEGORY_GROUP"].fillna("OTHER")

In [99]:
data = pd.get_dummies(data, columns=["CATEGORY_GROUP"], drop_first=True)

In [100]:
drop_cols = [
    "BUILDING_CLASS_CATEGORY",   # we replaced it with grouped dummies
    "SALE_PRICE",                # target is inflation adjusted now
    "TO_2024_FACTOR",            # used already
    "BOROUGH", "NEIGHBORHOOD",   # optional, you can keep later
    "ADDRESS", "ZIP_CODE"        # text id like, skip for now
]

data = data.drop(columns=[c for c in drop_cols if c in data.columns])

In [101]:
numeric_cols = [
    "YEAR_BUILT",
    "RESIDENTIAL_UNITS",
    "COMMERCIAL_UNITS",
    "TOTAL_UNITS",
    "LAND_SQUARE_FEET",
    "GROSS_SQUARE_FEET",
    "LOT",
    "SALE_YEAR",
    "SALE_MONTH",
    "SALE_DAY"
]
numeric_cols = [c for c in numeric_cols if c in data.columns]

dummy_cols = [c for c in data.columns if c.startswith("CATEGORY_GROUP_")]

feature_cols = numeric_cols + dummy_cols

X = data[feature_cols].astype(float)
y = data["INFLATION_ADJ_SALES"].astype(float)

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Features:", feature_cols)

X shape: (181400, 17)
y shape: (181400,)
Features: ['YEAR_BUILT', 'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS', 'TOTAL_UNITS', 'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'LOT', 'SALE_YEAR', 'SALE_MONTH', 'SALE_DAY', 'CATEGORY_GROUP_CONDO_COOP', 'CATEGORY_GROUP_MULTI_FAMILY_LARGE', 'CATEGORY_GROUP_MULTI_FAMILY_SMALL', 'CATEGORY_GROUP_OTHER', 'CATEGORY_GROUP_SINGLE_FAMILY', 'CATEGORY_GROUP_SPECIAL_USE', 'CATEGORY_GROUP_VACANT_LAND']

In [102]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,      # 80 percent train, 20 percent test
    random_state=42,    # ensures reproducible results
    shuffle=True
)

print("Train X shape:", X_train.shape)
print("Test  X shape:", X_test.shape)
print("Train y shape:", y_train.shape)
print("Test  y shape:", y_test.shape)

Train X shape: (145120, 17)
Test  X shape: (36280, 17)
Train y shape: (145120,)
Test  y shape: (36280,)

In [103]:
data = data[data["INFLATION_ADJ_SALES"] >= 10000]
print(data["INFLATION_ADJ_SALES"].describe())

count         176,106
mean        4,570,139
std        37,597,784
min            10,054
25%           628,656
50%         1,202,954
75%         2,716,366
max     5,441,001,504
Name: INFLATION_ADJ_SALES, dtype: float64

In [104]:
upper_limit = data["INFLATION_ADJ_SALES"].quantile(0.995)
data = data[data["INFLATION_ADJ_SALES"] <= upper_limit]

In [105]:
print(data["INFLATION_ADJ_SALES"].describe())

count       175,225
mean      2,980,287
std       6,658,793
min          10,054
25%         627,072
50%       1,194,016
75%       2,668,454
max     101,769,873
Name: INFLATION_ADJ_SALES, dtype: float64

In [106]:
upper_limit = data["INFLATION_ADJ_SALES"].quantile(0.995)
data = data[data["INFLATION_ADJ_SALES"] <= upper_limit]

In [107]:
print(data["INFLATION_ADJ_SALES"].describe())

count      174,348
mean     2,647,952
std      4,632,271
min         10,054
25%        623,363
50%      1,186,823
75%      2,627,296
max     48,605,047
Name: INFLATION_ADJ_SALES, dtype: float64

In [108]:
# Rebuild y
y = data["INFLATION_ADJ_SALES"].astype(float)

# Rebuild X
numeric_cols = [
    "YEAR_BUILT",
    "RESIDENTIAL_UNITS",
    "COMMERCIAL_UNITS",
    "TOTAL_UNITS",
    "LAND_SQUARE_FEET",
    "GROSS_SQUARE_FEET",
    "LOT",
    "SALE_YEAR",
    "SALE_MONTH",
    "SALE_DAY"
]

numeric_cols = [c for c in numeric_cols if c in data.columns]

dummy_cols = [c for c in data.columns if c.startswith("CATEGORY_GROUP_")]

feature_cols = numeric_cols + dummy_cols

X = data[feature_cols].astype(float)

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (174348, 17)
y shape: (174348,)

In [109]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(139478, 17) (139478,)
(34870, 17) (34870,)

### RF) Random Forest

In [110]:

rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred_train = rf.predict(X_train)
pred_test  = rf.predict(X_test)

print("Random Forest Results")
print("Train MAE :", mean_absolute_error(y_train, pred_train))
print("Test  MAE :", mean_absolute_error(y_test, pred_test))
print("Train RMSE:", np.sqrt(mean_squared_error(y_train, pred_train)))
print("Test RMSE :", np.sqrt(mean_squared_error(y_test, pred_test)))
print("Train R2  :", r2_score(y_train, pred_train))
print("Test R2  :", r2_score(y_test, pred_test))

Random Forest Results
Train MAE : 555441.165295635
Test  MAE : 1476930.9595481155
Train RMSE: 1230346.8618816277
Test RMSE : 3251463.2018810236
Train R2  : 0.9297169753399392
Test R2  : 0.4998371104915481

### Ridge regression

In [111]:
ridge_pipe = Pipeline([
    ("scaler", StandardScaler()),       # scale all features
    ("ridge", Ridge(alpha=100.0, random_state=42))
])

ridge_pipe.fit(X_train, y_train)

y_pred_train = ridge_pipe.predict(X_train)
y_pred_test = ridge_pipe.predict(X_test)

train_mae = mean_absolute_error(y_train, y_pred_train)
test_mae = mean_absolute_error(y_test, y_pred_test)

train_rmse = np.sqrt(mean_squared_error(y_train, y_pred_train))
test_rmse = np.sqrt(mean_squared_error(y_test, y_pred_test))

train_r2 = r2_score(y_train, y_pred_train)
test_r2 = r2_score(y_test, y_pred_test)

print("Ridge, alpha = 100")
print("Train MAE :", train_mae)
print("Test  MAE :", test_mae)
print("Train RMSE:", train_rmse)
print("Test  RMSE:", test_rmse)
print("Train R2  :", train_r2)
print("Test  R2  :", test_r2)

Ridge, alpha = 100
Train MAE : 2295395.10675652
Test  MAE : 2299126.912349474
Train RMSE: 4386606.964409899
Test  RMSE: 4385756.842954345
Train R2  : 0.1065859888446209
Test  R2  : 0.0899968868034784

In [112]:
alphas = [0.1, 1, 10, 100, 300, 1000]
results = []

for a in alphas:
    model = Pipeline([
        ("scaler", StandardScaler()),
        ("ridge", Ridge(alpha=a, random_state=42))
    ])
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    r2 = r2_score(y_test, preds)
    mae = mean_absolute_error(y_test, preds)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    results.append((a, r2, mae, rmse))

for a, r2, mae, rmse in results:
    print(f"alpha={a:<6}  Test R2={r2:.4f}  Test MAE={mae:,.0f}  Test RMSE={rmse:,.0f}")

alpha=0.1     Test R2=0.0900  Test MAE=2,297,998  Test RMSE=4,385,668
alpha=1       Test R2=0.0900  Test MAE=2,298,021  Test RMSE=4,385,676
alpha=10      Test R2=0.0900  Test MAE=2,298,219  Test RMSE=4,385,749
alpha=100     Test R2=0.0900  Test MAE=2,299,127  Test RMSE=4,385,757
alpha=300     Test R2=0.0903  Test MAE=2,300,168  Test RMSE=4,385,043
alpha=1000    Test R2=0.0905  Test MAE=2,303,495  Test RMSE=4,384,575

In [113]:
final_ridge = Pipeline([
    ("scaler", StandardScaler()),
    ("ridge", Ridge(alpha=1000, random_state=42))
])

final_ridge.fit(X_train, y_train)
pred = final_ridge.predict(X_test)

print("Final Ridge alpha=1000")
print("MAE :", mean_absolute_error(y_test, pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred)))
print("R2  :", r2_score(y_test, pred))

Final Ridge alpha=1000
MAE : 2303495.4477727413
RMSE: 4384574.894230722
R2  : 0.0904873070999993

### XGBoost regressor with the tree preprocessor

In [114]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.1.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.27.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [115]:
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [116]:
xgb_model = XGBRegressor(
    n_estimators=500,          # number of trees
    learning_rate=0.05,       # step size
    max_depth=6,              # tree depth
    subsample=0.8,            # row subsample
    colsample_bytree=0.8,     # feature subsample per tree
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1,
    tree_method="hist"        # if GPU available, you can try "gpu_hist"
)

In [117]:
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=-1, num_parallel_tree=None, ...)

In [118]:
y_pred_train_xgb = xgb_model.predict(X_train)
y_pred_test_xgb = xgb_model.predict(X_test)

train_mae_xgb = mean_absolute_error(y_train, y_pred_train_xgb)
test_mae_xgb = mean_absolute_error(y_test, y_pred_test_xgb)

train_rmse_xgb = np.sqrt(mean_squared_error(y_train, y_pred_train_xgb))
test_rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_test_xgb))

train_r2_xgb = r2_score(y_train, y_pred_train_xgb)
test_r2_xgb = r2_score(y_test, y_pred_test_xgb)

print("XGBoost results")
print("Train MAE :", train_mae_xgb)
print("Test  MAE :", test_mae_xgb)
print("Train RMSE:", train_rmse_xgb)
print("Test  RMSE:", test_rmse_xgb)
print("Train R2  :", train_r2_xgb)
print("Test  R2  :", test_r2_xgb)

XGBoost results
Train MAE : 1467139.3494166252
Test  MAE : 1602153.331580643
Train RMSE: 2944087.940946402
Test  RMSE: 3374171.960033232
Train R2  : 0.597563958677072
Test  R2  : 0.461372896898839

In [119]:
param_candidates = [
    {"max_depth": 4, "learning_rate": 0.05},
    {"max_depth": 6, "learning_rate": 0.05},
    {"max_depth": 6, "learning_rate": 0.03},
    {"max_depth": 8, "learning_rate": 0.05},
]

results = []

for params in param_candidates:
    model = XGBRegressor(
        n_estimators=600,
        learning_rate=params["learning_rate"],
        max_depth=params["max_depth"],
        subsample=0.8,
        colsample_bytree=0.8,
        objective="reg:squarederror",
        random_state=42,
        n_jobs=-1,
        tree_method="hist"
    )

    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    r2 = r2_score(y_test, preds)
    mae = mean_absolute_error(y_test, preds)
    results.append((params["max_depth"], params["learning_rate"], r2, mae))

for d, lr, r2, mae in results:
    print(f"max_depth={d}, lr={lr}  ->  Test R2={r2:.4f}, Test MAE={mae:,.0f}")

max_depth=4, lr=0.05  ->  Test R2=0.4140, Test MAE=1,691,947
max_depth=6, lr=0.05  ->  Test R2=0.4673, Test MAE=1,590,003
max_depth=6, lr=0.03  ->  Test R2=0.4508, Test MAE=1,624,374
max_depth=8, lr=0.05  ->  Test R2=0.5038, Test MAE=1,513,220

In [120]:
final_xgb = XGBRegressor(
    n_estimators=800,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1,
    tree_method="hist"
)

final_xgb.fit(X_train, y_train)

y_pred_train = final_xgb.predict(X_train)
y_pred_test = final_xgb.predict(X_test)

print("Final XGBoost")
print("Train R2:", r2_score(y_train, y_pred_train))
print("Test  R2:", r2_score(y_test, y_pred_test))
print("Test  MAE:", mean_absolute_error(y_test, y_pred_test))
print("Test  RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_test)))

Final XGBoost
Train R2: 0.5940599098199599
Test  R2: 0.46202493861434935
Test  MAE: 1603738.9161380567
Test  RMSE: 3372129.0187258353

### Linear Regression

In [121]:
linreg_pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("linreg", LinearRegression())
])

linreg_pipe.fit(X_train, y_train)

y_pred_train = linreg_pipe.predict(X_train)
y_pred_test  = linreg_pipe.predict(X_test)

train_mae  = mean_absolute_error(y_train, y_pred_train)
test_mae   = mean_absolute_error(y_test, y_pred_test)
train_rmse = np.sqrt(mean_squared_error(y_train, y_pred_train))
test_rmse  = np.sqrt(mean_squared_error(y_test, y_pred_test))
train_r2   = r2_score(y_train, y_pred_train)
test_r2    = r2_score(y_test, y_pred_test)

print("Linear Regression Results")
print("Train MAE :", train_mae)
print("Test  MAE :", test_mae)
print("Train RMSE:", train_rmse)
print("Test  RMSE:", test_rmse)
print("Train R2  :", train_r2)
print("Test  R2  :", test_r2)

Linear Regression Results
Train MAE : 2294446.3594343616
Test  MAE : 2297995.220891843
Train RMSE: 4386066.521850722
Test  RMSE: 4385667.074875985
Train R2  : 0.10680611762066061
Test  R2  : 0.09003413847870223

### Gradient Boosting (Histogram-based)

In [122]:
hgb = HistGradientBoostingRegressor(
    max_depth=8,
    learning_rate=0.05,
    max_iter=600,
    min_samples_leaf=20,
    l2_regularization=0.0,
    random_state=42
)

hgb.fit(X_train, y_train)

pred_train = hgb.predict(X_train)
pred_test = hgb.predict(X_test)

print("HGB Results")
print("Train MAE :", mean_absolute_error(y_train, pred_train))
print("Test  MAE :", mean_absolute_error(y_test, pred_test))
print("Train RMSE:", np.sqrt(mean_squared_error(y_train, pred_train)))
print("Test  RMSE:", np.sqrt(mean_squared_error(y_test, pred_test)))
print("Train R2  :", r2_score(y_train, pred_train))
print("Test  R2  :", r2_score(y_test, pred_test))

HGB Results
Train MAE : 1574103.68729905
Test  MAE : 1639055.9904598703
Train RMSE: 3215960.2409801525
Test  RMSE: 3442210.7248837957
Train R2  : 0.5198060839563563
Test  R2  : 0.4394315055143412

In [123]:
hgbA = HistGradientBoostingRegressor(
    max_depth=10,
    learning_rate=0.03,
    max_iter=900,
    min_samples_leaf=20,
    random_state=42
)

hgbA.fit(X_train, y_train)
predA = hgbA.predict(X_test)

print("HGB A (deep trees)")
print("Test MAE:", mean_absolute_error(y_test, predA))
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, predA)))
print("Test R2 :", r2_score(y_test, predA))

HGB A (deep trees)
Test MAE: 1639271.7849977766
Test RMSE: 3432398.1021729666
Test R2 : 0.4426229468881604

In [124]:
hgbB = HistGradientBoostingRegressor(
    max_depth=8,
    learning_rate=0.02,
    max_iter=1500,
    min_samples_leaf=20,
    random_state=42
)

hgbB.fit(X_train, y_train)
predB = hgbB.predict(X_test)

print("HGB B (slow LR)")
print("Test MAE:", mean_absolute_error(y_test, predB))
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, predB)))
print("Test R2 :", r2_score(y_test, predB))

HGB B (slow LR)
Test MAE: 1611696.9993433752
Test RMSE: 3398617.7868573093
Test R2 : 0.4535399333905873

In [125]:
hgbC = HistGradientBoostingRegressor(
    max_depth=8,
    learning_rate=0.05,
    max_iter=700,
    min_samples_leaf=5,
    random_state=42
)

hgbC.fit(X_train, y_train)
predC = hgbC.predict(X_test)

print("HGB C (small leaves)")
print("Test MAE:", mean_absolute_error(y_test, predC))
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, predC)))
print("Test R2 :", r2_score(y_test, predC))

HGB C (small leaves)
Test MAE: 1642230.2742876792
Test RMSE: 3424462.004589395
Test R2 : 0.4451974064063142

###  KNN

In [126]:
def evaluate_knn(k):
    knn_pipe = Pipeline([
        ("scaler", StandardScaler()),
        ("knn", KNeighborsRegressor(n_neighbors=k, weights='distance'))
    ])

    knn_pipe.fit(X_train, y_train)
    preds = knn_pipe.predict(X_test)

    mae  = mean_absolute_error(y_test, preds)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    r2   = r2_score(y_test, preds)

    print(f"k={k:<3}  Test MAE={mae:,.0f}  Test RMSE={rmse:,.0f}  Test R2={r2:.4f}")
    return mae, rmse, r2

# evaluate a few values
for k in [3, 5, 7, 9, 15, 25, 35, 50]:
    evaluate_knn(k)

k=3    Test MAE=2,001,517  Test RMSE=4,190,382  Test R2=0.1693
k=5    Test MAE=1,932,996  Test RMSE=4,012,055  Test R2=0.2385
k=7    Test MAE=1,899,877  Test RMSE=3,936,454  Test R2=0.2669
k=9    Test MAE=1,886,079  Test RMSE=3,901,854  Test R2=0.2797
k=15   Test MAE=1,865,512  Test RMSE=3,864,319  Test R2=0.2935
k=25   Test MAE=1,851,337  Test RMSE=3,847,186  Test R2=0.2998
k=35   Test MAE=1,847,008  Test RMSE=3,845,111  Test R2=0.3005
k=50   Test MAE=1,844,022  Test RMSE=3,845,074  Test R2=0.3005

### Huber Regression

In [127]:
huber_pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("huber", HuberRegressor(epsilon=1.35, max_iter=300))
])

huber_pipe.fit(X_train, y_train)
pred = huber_pipe.predict(X_test)

print("Huber Regression Results")
print("MAE :", mean_absolute_error(y_test, pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred)))
print("R2  :", r2_score(y_test, pred))

Huber Regression Results
MAE : 1927650.4210835423
RMSE: 4540031.032016384
R2  : 0.02485000815112315

### LASSO

In [128]:
lasso_pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("lasso", Lasso(alpha=0.001, max_iter=5000, random_state=42))
])

lasso_pipe.fit(X_train, y_train)

pred = lasso_pipe.predict(X_test)

print("LASSO Results")
print("MAE :", mean_absolute_error(y_test, pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred)))
print("R2  :", r2_score(y_test, pred))

LASSO Results
MAE : 2298028.784916199
RMSE: 4385693.1789742885
R2  : 0.09002330596059738

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.342e+18, tolerance: 3.004e+14

In [129]:
alphas = [0.0001, 0.001, 0.01, 0.1, 1]

for a in alphas:
    model = Pipeline([
        ("scaler", StandardScaler()),
        ("lasso", Lasso(alpha=a, max_iter=5000, random_state=42))
    ])
    model.fit(X_train, y_train)
    preds = model.predict(X_test)

    print(f"alpha={a:<6}  R2={r2_score(y_test, preds):.4f}  MAE={mean_absolute_error(y_test, preds):,.0f}")

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.342e+18, tolerance: 3.004e+14

alpha=0.0001  R2=0.0900  MAE=2,298,029

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.342e+18, tolerance: 3.004e+14

alpha=0.001   R2=0.0900  MAE=2,298,029

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.341e+18, tolerance: 3.004e+14

alpha=0.01    R2=0.0900  MAE=2,298,029

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.338e+18, tolerance: 3.004e+14

alpha=0.1     R2=0.0900  MAE=2,298,029
alpha=1       R2=0.0900  MAE=2,298,030

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.305e+18, tolerance: 3.004e+14

### The Multilayer Perceptron (MLP)

In [130]:
mlp = Pipeline([
    ("scaler", StandardScaler()),
    ("mlp", MLPRegressor(
        hidden_layer_sizes=(128, 64, 32),
        activation="relu",
        solver="adam",
        learning_rate_init=0.001,
        max_iter=500,
        random_state=42
    ))
])

mlp.fit(X_train, y_train)

pred_train = mlp.predict(X_train)
pred_test = mlp.predict(X_test)

print("MLP Results")
print("Train MAE", mean_absolute_error(y_train, pred_train))
print("Test MAE", mean_absolute_error(y_test, pred_test))
print("Train RMSE", np.sqrt(mean_squared_error(y_train, pred_train)))
print("Test RMSE", np.sqrt(mean_squared_error(y_test, pred_test)))
print("Train R2", r2_score(y_train, pred_train))
print("Test R2", r2_score(y_test, pred_test))

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning:

Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.

MLP Results
Train MAE 1867112.7088782392
Test MAE 1882180.9512225296
Train RMSE 3729926.512839499
Test RMSE 3776920.7207923774
Train R2 0.35405452191283315
Test R2 0.32511540260078653

### LSTM

In [131]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# reshape to (samples, timesteps, features_per_step)
n_timesteps = X_train_scaled.shape[1]   # 17
X_train_lstm = X_train_scaled.reshape(X_train_scaled.shape[0], n_timesteps, 1)
X_test_lstm  = X_test_scaled.reshape(X_test_scaled.shape[0], n_timesteps, 1)

print("LSTM train shape:", X_train_lstm.shape)
print("LSTM test shape :", X_test_lstm.shape)

LSTM train shape: (139478, 17, 1)
LSTM test shape : (34870, 17, 1)

In [132]:
model = Sequential([
    LSTM(64, input_shape=(n_timesteps, 1)),
    Dense(32, activation="relu"),
    Dense(1)  # regression output
])

model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 64)             │        16,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,009 (74.25 KB)

 Trainable params: 19,009 (74.25 KB)

 Non-trainable params: 0 (0.00 B)

In [133]:
es = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train_lstm,
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=256,
    callbacks=[es],
    verbose=1
)

Epoch 1/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - loss: 27735319642112.0000 - mae: 2620407.5000 - val_loss: 29838700183552.0000 - val_mae: 2691980.0000
Epoch 2/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - loss: 28859799961600.0000 - mae: 2662423.5000 - val_loss: 29829145559040.0000 - val_mae: 2690205.5000
Epoch 3/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 28464946085888.0000 - mae: 2638105.2500 - val_loss: 29814222225408.0000 - val_mae: 2687431.5000
Epoch 4/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - loss: 27456174030848.0000 - mae: 2587970.5000 - val_loss: 29794580299776.0000 - val_mae: 2683772.2500
Epoch 5/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - loss: 28115300515840.0000 - mae: 2625344.5000 - val_loss: 29770878287872.0000 - val_mae: 2679360.7500
Epoch 6/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - loss: 28687294529536.0000 - mae: 2642625.5000 - val_loss: 29743478996992.0000 - val_mae: 2674282.2500
Epoch 7/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 28439954325504.0000 - mae: 2636562.2500 - val_loss: 29712715874304.0000 - val_mae: 2668658.5000
Epoch 8/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - loss: 28090877083648.0000 - mae: 2615455.7500 - val_loss: 29678700068864.0000 - val_mae: 2662591.5000
Epoch 9/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 27322440744960.0000 - mae: 2591405.0000 - val_loss: 29641674850304.0000 - val_mae: 2656061.0000
Epoch 10/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 28239768584192.0000 - mae: 2606213.7500 - val_loss: 29601833156608.0000 - val_mae: 2649081.5000
Epoch 11/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - loss: 28153751797760.0000 - mae: 2583109.5000 - val_loss: 29559273553920.0000 - val_mae: 2641735.5000
Epoch 12/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - loss: 28599822319616.0000 - mae: 2613116.7500 - val_loss: 29514027499520.0000 - val_mae: 2634085.0000
Epoch 13/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - loss: 27613619814400.0000 - mae: 2570788.2500 - val_loss: 29466193559552.0000 - val_mae: 2626113.7500
Epoch 14/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - loss: 28127126355968.0000 - mae: 2588959.2500 - val_loss: 29415840940032.0000 - val_mae: 2618055.2500
Epoch 15/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 28012483444736.0000 - mae: 2573665.2500 - val_loss: 29363059818496.0000 - val_mae: 2609771.2500
Epoch 16/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 28648297988096.0000 - mae: 2574520.2500 - val_loss: 29307881652224.0000 - val_mae: 2601143.0000
Epoch 17/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - loss: 27661409714176.0000 - mae: 2543016.7500 - val_loss: 29250306441216.0000 - val_mae: 2592216.2500
Epoch 18/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 27559844642816.0000 - mae: 2528183.2500 - val_loss: 29190376128512.0000 - val_mae: 2583006.5000
Epoch 19/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 27699890356224.0000 - mae: 2529042.7500 - val_loss: 29128409481216.0000 - val_mae: 2573515.5000
Epoch 20/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - loss: 26535299907584.0000 - mae: 2487899.2500 - val_loss: 29064003846144.0000 - val_mae: 2563715.7500
Epoch 21/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - loss: 27355040972800.0000 - mae: 2518365.0000 - val_loss: 28997616402432.0000 - val_mae: 2553666.5000
Epoch 22/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 27312915480576.0000 - mae: 2493532.5000 - val_loss: 28929077280768.0000 - val_mae: 2543311.7500
Epoch 23/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - loss: 27132268904448.0000 - mae: 2476661.5000 - val_loss: 28858541670400.0000 - val_mae: 2532648.0000
Epoch 24/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - loss: 27260998385664.0000 - mae: 2478929.7500 - val_loss: 28786093457408.0000 - val_mae: 2521669.5000
Epoch 25/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 27137631322112.0000 - mae: 2467741.7500 - val_loss: 28711705378816.0000 - val_mae: 2510372.0000
Epoch 26/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - loss: 27057169891328.0000 - mae: 2451063.0000 - val_loss: 28635272577024.0000 - val_mae: 2498746.2500
Epoch 27/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - loss: 26642797821952.0000 - mae: 2439935.0000 - val_loss: 28557122207744.0000 - val_mae: 2486830.7500
Epoch 28/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 27054047232000.0000 - mae: 2431002.0000 - val_loss: 28477059235840.0000 - val_mae: 2474608.0000
Epoch 29/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - loss: 27459758063616.0000 - mae: 2441975.5000 - val_loss: 28395475828736.0000 - val_mae: 2462142.5000
Epoch 30/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 27240381284352.0000 - mae: 2412508.5000 - val_loss: 28312082579456.0000 - val_mae: 2449394.0000
Epoch 31/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 26267109818368.0000 - mae: 2369106.7500 - val_loss: 28227147923456.0000 - val_mae: 2436415.0000
Epoch 32/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - loss: 26827881971712.0000 - mae: 2389141.0000 - val_loss: 28140673957888.0000 - val_mae: 2423208.0000
Epoch 33/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - loss: 27028122238976.0000 - mae: 2384147.0000 - val_loss: 28052805386240.0000 - val_mae: 2409845.2500
Epoch 34/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - loss: 26827370266624.0000 - mae: 2380307.7500 - val_loss: 27963372339200.0000 - val_mae: 2396290.2500
Epoch 35/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 29s 66ms/step - loss: 25939673088000.0000 - mae: 2335060.0000 - val_loss: 27872647446528.0000 - val_mae: 2382592.0000
Epoch 36/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 29s 39ms/step - loss: 26682150879232.0000 - mae: 2333339.5000 - val_loss: 27780576182272.0000 - val_mae: 2368805.5000
Epoch 37/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - loss: 26753672151040.0000 - mae: 2334740.5000 - val_loss: 27687198392320.0000 - val_mae: 2354975.2500
Epoch 38/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 26136522260480.0000 - mae: 2300904.2500 - val_loss: 27592759443456.0000 - val_mae: 2341201.2500
Epoch 39/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 25885946150912.0000 - mae: 2291081.7500 - val_loss: 27497278210048.0000 - val_mae: 2327471.5000
Epoch 40/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - loss: 26340900208640.0000 - mae: 2279718.2500 - val_loss: 27400666611712.0000 - val_mae: 2313788.0000
Epoch 41/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - loss: 25958566330368.0000 - mae: 2264360.5000 - val_loss: 27303075643392.0000 - val_mae: 2300213.5000
Epoch 42/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 25725373513728.0000 - mae: 2238818.2500 - val_loss: 27204564025344.0000 - val_mae: 2286808.0000
Epoch 43/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - loss: 25666179301376.0000 - mae: 2240522.7500 - val_loss: 27105419067392.0000 - val_mae: 2273626.7500
Epoch 44/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 25797897224192.0000 - mae: 2232492.7500 - val_loss: 27005303128064.0000 - val_mae: 2260680.2500
Epoch 45/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - loss: 25089462501376.0000 - mae: 2189179.5000 - val_loss: 26904402853888.0000 - val_mae: 2248034.0000
Epoch 46/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - loss: 24928048906240.0000 - mae: 2184791.0000 - val_loss: 26803125092352.0000 - val_mae: 2235749.0000
Epoch 47/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - loss: 25279888097280.0000 - mae: 2191182.0000 - val_loss: 26701310459904.0000 - val_mae: 2223812.2500
Epoch 48/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - loss: 25129601990656.0000 - mae: 2171883.5000 - val_loss: 26599068008448.0000 - val_mae: 2212283.5000
Epoch 49/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 25440416694272.0000 - mae: 2174000.5000 - val_loss: 26496391446528.0000 - val_mae: 2201191.7500
Epoch 50/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - loss: 24881525686272.0000 - mae: 2146593.7500 - val_loss: 26393299648512.0000 - val_mae: 2190627.5000

In [134]:
y_pred_train = model.predict(X_train_lstm).ravel()
y_pred_test  = model.predict(X_test_lstm).ravel()

train_mae = mean_absolute_error(y_train, y_pred_train)
test_mae  = mean_absolute_error(y_test, y_pred_test)

train_rmse = np.sqrt(mean_squared_error(y_train, y_pred_train))
test_rmse  = np.sqrt(mean_squared_error(y_test, y_pred_test))

train_r2 = r2_score(y_train, y_pred_train)
test_r2  = r2_score(y_test, y_pred_test)

print("LSTM Regression Results")
print("Train MAE :", train_mae)
print("Test  MAE :", test_mae)
print("Train RMSE:", train_rmse)
print("Test  RMSE:", test_rmse)
print("Train R2  :", train_r2)
print("Test  R2  :", test_r2)

4359/4359 ━━━━━━━━━━━━━━━━━━━━ 17s 4ms/step
1090/1090 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step
LSTM Regression Results
Train MAE : 2151704.9872457613
Test  MAE : 2139220.9419054124
Train RMSE: 5017411.982238524
Test  RMSE: 4973557.341912085
Train R2  : -0.16883938417177924
Test  R2  : -0.17027529674043862

### Deep and Cross Network

In [137]:
from tensorflow.keras.layers import Layer

In [138]:
class CrossLayer(Layer):
    def __init__(self, num_layers, **kwargs):
        super().__init__(**kwargs)
        self.num_layers = num_layers
        self.w = []
        self.b = []

    def build(self, input_shape):
        input_dim = int(input_shape[-1])
        for i in range(self.num_layers):
            self.w.append(
                self.add_weight(
                    shape=(input_dim, 1),
                    initializer="glorot_uniform",
                    name=f"w_{i}"
                )
            )
            self.b.append(
                self.add_weight(
                    shape=(input_dim,),
                    initializer="zeros",
                    name=f"b_{i}"
                )
            )

    def call(self, x0):
        x = x0
        for i in range(self.num_layers):
            # xw shape: (batch, 1)
            xw = tf.matmul(x, self.w[i])   # linear projection
            # broadcast to (batch, input_dim) and elementwise multiply with x0
            cross = x0 * xw + self.b[i]
            x = x + cross
        return x


def build_dcn(input_dim, cross_layers=3, deep_units=[128, 64, 32]):
    inp = Input(shape=(input_dim,))

    # cross network
    cross_out = CrossLayer(num_layers=cross_layers, name="cross_layer")(inp)

    # deep network
    deep = inp
    for i, units in enumerate(deep_units):
        deep = Dense(units, activation="relu", name=f"deep_dense_{i}")(deep)

    # use Keras Concatenate instead of tf.concat
    combined = Concatenate(name="combine_cross_deep")([cross_out, deep])

    out = Dense(1, name="output")(combined)

    model = Model(inputs=inp, outputs=out, name="DeepAndCrossNetwork")
    model.compile(optimizer="adam", loss="mse", metrics=["mae"])
    return model

In [139]:
n_features = X_train.shape[1]

In [140]:
dcn = build_dcn(n_features, cross_layers=3, deep_units=[128, 64, 32])
dcn.summary()

Model: "DeepAndCrossNetwork"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_1       │ (None, 17)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ deep_dense_0        │ (None, 128)       │      2,304 │ input_layer_1[0]… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ deep_dense_1        │ (None, 64)        │      8,256 │ deep_dense_0[0][… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cross_layer         │ (None, 17)        │        102 │ input_layer_1[0]… │
│ (CrossLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ deep_dense_2        │ (None, 32)        │      2,080 │ deep_dense_1[0][… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ combine_cross_deep  │ (None, 49)        │          0 │ cross_layer[0][0… │
│ (Concatenate)       │                   │            │ deep_dense_2[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ output (Dense)      │ (None, 1)         │         50 │ combine_cross_de… │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 12,792 (49.97 KB)

 Trainable params: 12,792 (49.97 KB)

 Non-trainable params: 0 (0.00 B)

In [141]:
es = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

history = dcn.fit(
    X_train_scaled,
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=256,
    callbacks=[es],
    verbose=1
)

pred_train = dcn.predict(X_train_scaled).flatten()
pred_test  = dcn.predict(X_test_scaled).flatten()

print("DCN Results")
print("Train MAE :", mean_absolute_error(y_train, pred_train))
print("Test  MAE :", mean_absolute_error(y_test, pred_test))
print("Train RMSE:", np.sqrt(mean_squared_error(y_train, pred_train)))
print("Test  RMSE:", np.sqrt(mean_squared_error(y_test, pred_test)))
print("Train R2  :", r2_score(y_train, pred_train))
print("Test  R2  :", r2_score(y_test, pred_test))

Epoch 1/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 28160968097792.0000 - mae: 2627501.0000 - val_loss: 83322659143680.0000 - val_mae: 2624188.0000
Epoch 2/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 25507812868096.0000 - mae: 2371425.5000 - val_loss: 65761569669120.0000 - val_mae: 2162588.2500
Epoch 3/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 21497861111808.0000 - mae: 2136197.7500 - val_loss: 167634251284480.0000 - val_mae: 2348721.2500
Epoch 4/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 19962242531328.0000 - mae: 2272014.5000 - val_loss: 422136330059776.0000 - val_mae: 2474944.7500
Epoch 5/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 19287613898752.0000 - mae: 2308232.0000 - val_loss: 1574877937008640.0000 - val_mae: 2586721.0000
Epoch 6/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 20200497872896.0000 - mae: 2354358.7500 - val_loss: 5861108866875392.0000 - val_mae: 2805510.5000
Epoch 7/50
436/436 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 19839559139328.0000 - mae: 2326691.2500 - val_loss: 27585007279144960.0000 - val_mae: 3359394.7500
4359/4359 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step
1090/1090 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
DCN Results
Train MAE : 2099858.173030763
Test  MAE : 2090252.0368524808
Train RMSE: 5540037.247388511
Test  RMSE: 4686612.074147726
Train R2  : -0.4250190849189972
Test  R2  : -0.03913456924255598

##  FROM SCRATCH

### RIDGE

In [142]:

class RidgeScratch:
    def __init__(self, alpha=1.0):
        """
        Simple Ridge Regression from scratch, with:
        - L2 penalty on weights
        - no penalty on intercept
        - internal standardisation of X
        """
        self.alpha = float(alpha)
        self.coef_ = None           # shape (n_features,)
        self.intercept_ = None      # scalar
        self.x_mean_ = None
        self.x_std_ = None
        self.is_fitted_ = False

    def _standardise(self, X):
        """
        Standardise features using training mean and std.
        Avoid division by zero if a feature has zero variance.
        """
        X = np.asarray(X, dtype=float)
        X_std_safe = np.where(self.x_std_ == 0, 1.0, self.x_std_)
        return (X - self.x_mean_) / X_std_safe

    def fit(self, X, y):
        """
        Closed form ridge:
        beta = (X^T X + alpha I)^-1 X^T y
        with:
        - design matrix [1, X_standardised]
        - intercept column not regularised
        """
        X = np.asarray(X, dtype=float)
        y = np.asarray(y, dtype=float).reshape(-1, 1)

        n_samples, n_features = X.shape

        # compute mean and std on training data
        self.x_mean_ = X.mean(axis=0)
        self.x_std_ = X.std(axis=0)

        # standardise X
        Xs = self._standardise(X)                      # shape (n_samples, n_features)

        # design matrix with bias column
        X_design = np.concatenate(
            [np.ones((n_samples, 1)), Xs],
            axis=1
        )                                              # shape (n_samples, n_features + 1)

        # ridge matrix, do not regularise intercept term
        n_params = X_design.shape[1]
        I = np.eye(n_params)
        I[0, 0] = 0.0                                  # no penalty on intercept

        # closed form ridge solution
        A = X_design.T @ X_design + self.alpha * I
        b = X_design.T @ y
        beta = np.linalg.solve(A, b)                   # shape (n_features + 1, 1)

        # store parameters
        self.intercept_ = float(beta[0, 0])
        self.coef_ = beta[1:, 0]                       # shape (n_features,)

        self.is_fitted_ = True
        return self

    def predict(self, X):
        """
        Predict using the fitted ridge model.
        """
        if not self.is_fitted_:
            raise RuntimeError("You must call fit before predict.")

        X = np.asarray(X, dtype=float)
        Xs = self._standardise(X)

        # y = intercept + X_standardised · coef
        return self.intercept_ + Xs @ self.coef_

In [143]:
ridge_scratch = RidgeScratch(alpha=100.0)   # you can try 10, 100, 300 etc
ridge_scratch.fit(X_train, y_train)

print("Intercept:", ridge_scratch.intercept_)
print("Number of coefficients:", len(ridge_scratch.coef_))
print("Should equal n_features:", X_train.shape[1])

Intercept: 2649913.889568792
Number of coefficients: 17
Should equal n_features: 17

In [144]:
y_pred_train = ridge_scratch.predict(X_train)
y_pred_test  = ridge_scratch.predict(X_test)

train_mae = mean_absolute_error(y_train, y_pred_train)
test_mae  = mean_absolute_error(y_test, y_pred_test)

train_rmse = np.sqrt(mean_squared_error(y_train, y_pred_train))
test_rmse  = np.sqrt(mean_squared_error(y_test, y_pred_test))

train_r2 = r2_score(y_train, y_pred_train)
test_r2  = r2_score(y_test, y_pred_test)

print("RidgeScratch (alpha=100)")
print("Train MAE :", train_mae)
print("Test  MAE :", test_mae)
print("Train RMSE:", train_rmse)
print("Test  RMSE:", test_rmse)
print("Train R2  :", train_r2)
print("Test  R2  :", test_r2)

RidgeScratch (alpha=100)
Train MAE : 2295395.10675652
Test  MAE : 2299126.912349474
Train RMSE: 4386606.964409899
Test  RMSE: 4385756.842954345
Train R2  : 0.1065859888446209
Test  R2  : 0.0899968868034785

In [145]:
for a in [1, 10, 100, 300, 1000]:
    m = RidgeScratch(alpha=a).fit(X_train, y_train)
    preds = m.predict(X_test)
    print(f"alpha={a:<5}  R2={r2_score(y_test, preds):.4f}  MAE={mean_absolute_error(y_test, preds):,.0f}")

alpha=1      R2=0.0900  MAE=2,298,021
alpha=10     R2=0.0900  MAE=2,298,219
alpha=100    R2=0.0900  MAE=2,299,127
alpha=300    R2=0.0903  MAE=2,300,168
alpha=1000   R2=0.0905  MAE=2,303,495

## HYBRID MODELS

In [146]:
### Simple average hybrid (XGB + RF + HGB)

In [147]:
# 1. Reuse your existing XGBoost model
# xgb_model already exists in your globals

# 2. Train Random Forest
rf_model = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)

# 3. Train Histogram Gradient Boosting (your best config)
hgb_model = HistGradientBoostingRegressor(
    max_depth=8,
    learning_rate=0.05,
    max_iter=700,
    min_samples_leaf=5,
    random_state=42
)
hgb_model.fit(X_train, y_train)

# 4. Predictions for each model
pred_xgb_train = xgb_model.predict(X_train)
pred_xgb_test  = xgb_model.predict(X_test)

pred_rf_train = rf_model.predict(X_train)
pred_rf_test  = rf_model.predict(X_test)

pred_hgb_train = hgb_model.predict(X_train)
pred_hgb_test  = hgb_model.predict(X_test)

# 5. Simple average hybrid
pred_ens_train = (pred_xgb_train + pred_rf_train + pred_hgb_train) / 3.0
pred_ens_test  = (pred_xgb_test  + pred_rf_test  + pred_hgb_test)  / 3.0

train_mae_ens = mean_absolute_error(y_train, pred_ens_train)
test_mae_ens  = mean_absolute_error(y_test, pred_ens_test)
train_rmse_ens = np.sqrt(mean_squared_error(y_train, pred_ens_train))
test_rmse_ens  = np.sqrt(mean_squared_error(y_test, pred_ens_test))
train_r2_ens = r2_score(y_train, pred_ens_train)
test_r2_ens  = r2_score(y_test, pred_ens_test)

print("Hybrid (simple average XGB + RF + HGB)")
print("Train MAE :", train_mae_ens)
print("Test  MAE :", test_mae_ens)
print("Train RMSE:", train_rmse_ens)
print("Test  RMSE:", test_rmse_ens)
print("Train R2  :", train_r2_ens)
print("Test  R2  :", test_r2_ens)

Hybrid (simple average XGB + RF + HGB)
Train MAE : 1167618.060194177
Test  MAE : 1529084.3191298903
Train RMSE: 2368405.300094086
Test  RMSE: 3253724.4543364826
Train R2  : 0.739560195849001
Test  R2  : 0.4991411851368641